import type { HotelEntry } from '../types';

export const HOTEL_DIRECTORY: HotelEntry[] = [
  {
    id: 'forestis-dolomites',
    slug: 'forestis-dolomites',
    name: 'Forestis Dolomites',
    destination: 'Dolomiti',
    destinationSlug: 'dolomiti',
    destinationHref: '/destinazioni/italia',
    country: 'Italia',
    region: 'Alto Adige',
    category: 'Wellness in quota',
    image:
      'https://images.unsplash.com/photo-1578898886225-c7b38bfe1d45?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/hotel/it/forestis-dolomites.it.html',
    priceHint: 'EUR 420',
    rating: 9.4,
    badge: 'Nostra scelta',
    summary:
      'Un rifugio contemporaneo in quota, pensato per chi vuole silenzio, spa e una vista che basta da sola a cambiare il ritmo.',
    fit: 'Perfetto per un viaggio lento di coppia, per chi vuole piu atmosfera che attivita continue.',
    idealFor: ['coppie', 'wellness', 'design', 'paesaggio'],
    pros: [
      'Vista fortissima gia dall arrivo',
      'Spa e camere coerenti col prezzo',
      'Esperienza high-end ma non fredda',
    ],
    cons: ['Prezzo alto', 'Meno adatto se vuoi uscire spesso la sera'],
    editorialNote:
      'Lo consigliamo quando il viaggio ruota attorno al luogo e al tempo lento, non quando serve una base pratica per fare tutto.',
    relatedGuideHref: '/itinerari/dolomiti-rifugi-design',
    mapLabel: 'Bressanone / Plose',
    published: true,
  },
  {
    id: 'adler-lodge-ritten',
    slug: 'adler-lodge-ritten',
    name: 'Adler Lodge Ritten',
    destination: 'Dolomiti',
    destinationSlug: 'dolomiti',
    destinationHref: '/destinazioni/italia',
    country: 'Italia',
    region: 'Alto Adige',
    category: 'Lodge contemporaneo',
    image:
      'https://images.unsplash.com/photo-1564501049412-61c2a3083791?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/hotel/it/adler-lodge-ritten.it.html',
    priceHint: 'EUR 310',
    rating: 9.2,
    summary:
      'Una base montana calda e pulita, con un equilibrio convincente tra comfort, panorama e accesso ai sentieri.',
    fit: 'Funziona bene se vuoi stare in montagna con taglio premium ma meno radicale di un resort super iconico.',
    idealFor: ['coppie', 'natura', 'hiking soft'],
    pros: [
      'Buona relazione tra comfort e atmosfera',
      'Base solida per 2-3 notti',
      'Ottimo per staccare',
    ],
    cons: ['Meno memorabile dei top iconici', 'Serve scegliere bene il periodo'],
    editorialNote:
      'Lo vediamo come scelta intelligente quando vuoi design e montagna, ma senza spingerti sul prezzo piu alto del cluster.',
    relatedGuideHref: '/guide',
    mapLabel: 'Renon',
    published: true,
  },
  {
    id: 'icaro-hotel',
    slug: 'icaro-hotel',
    name: 'Icaro Hotel',
    destination: 'Dolomiti',
    destinationSlug: 'dolomiti',
    destinationHref: '/destinazioni/italia',
    country: 'Italia',
    region: 'Alto Adige',
    category: 'Design di montagna',
    image:
      'https://images.unsplash.com/photo-1586375300773-8384e3e4916f?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/hotel/it/icaro.it.html',
    priceHint: 'EUR 240',
    rating: 9.0,
    summary:
      'Una struttura di montagna dal taglio piu essenziale, con una forte vocazione paesaggio e un posizionamento piu accessibile.',
    fit: 'Buona scelta se vuoi il lato piu grafico delle Dolomiti senza puntare al lusso piu estremo.',
    idealFor: ['design', 'mountain stay', 'weekend'],
    pros: ['Look curato', 'Prezzo piu leggibile', 'Buona coerenza visuale'],
    cons: ['Meno servizi rispetto ai resort piu alti di gamma', 'Esperienza piu asciutta'],
    editorialNote:
      'Lo teniamo nella shortlist quando il criterio principale e stare bene in un bel posto, non accumulare servizi.',
    relatedGuideHref: '/itinerari/dolomiti-rifugi-design',
    mapLabel: 'Alpe di Siusi',
    published: true,
  },
  {
    id: 'borgo-egnazia',
    slug: 'borgo-egnazia',
    name: 'Borgo Egnazia',
    destination: 'Puglia',
    destinationSlug: 'puglia',
    destinationHref: '/destinazioni/italia',
    country: 'Italia',
    region: 'Puglia',
    category: 'Resort iconico',
    image:
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/hotel/it/borgo-egnazia.it.html',
    priceHint: 'EUR 650',
    rating: 9.5,
    badge: 'Nostra scelta',
    summary:
      'Il classico caso in cui il soggiorno diventa quasi la destinazione: grande impatto, forte identita, hospitality molto costruita.',
    fit: 'Da scegliere se vuoi un soggiorno importante, con budget alto e aspettativa di esperienza completa.',
    idealFor: ['luxury', 'honeymoon', 'hospitality', 'Puglia premium'],
    pros: ['Identita fortissima', 'Servizio di livello', 'Perfetto per momenti speciali'],
    cons: ['Prezzo molto alto', 'Meno adatto se vuoi una Puglia spontanea e mobile'],
    editorialNote:
      'Lo consigliamo quando il viaggio ha un taglio celebrativo. Non e la scelta giusta per chi vuole muoversi in modo piu libero.',
    relatedGuideHref: '/destinazioni/italia',
    mapLabel: 'Savelletri',
    published: true,
  },
  {
    id: 'masseria-trapana',
    slug: 'masseria-trapana',
    name: 'Masseria Trapana',
    destination: 'Puglia',
    destinationSlug: 'puglia',
    destinationHref: '/destinazioni/italia',
    country: 'Italia',
    region: 'Puglia',
    category: 'Masseria intima',
    image:
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/hotel/it/masseria-trapana.it.html',
    priceHint: 'EUR 380',
    rating: 9.6,
    summary:
      'Una delle opzioni piu coerenti per chi cerca una Puglia lenta, bianca, quieta e con meno rumore da resort.',
    fit: 'Molto buona per coppie che vogliono design morbido, privacy e un soggiorno piu raccolto.',
    idealFor: ['coppie', 'slow travel', 'masseria', 'quiet luxury'],
    pros: ['Atmosfera forte', 'Scala umana', 'Molto piu intima dei grandi resort'],
    cons: ['Serve auto', 'Meno adatta a chi vuole vita serale'],
    editorialNote:
      'Qui il valore e la calma. Se il viaggio e centrato su mare e movimento continuo, meglio orientarsi altrove.',
    relatedGuideHref: '/guide?cat=dove-dormire',
    mapLabel: 'Puglia centrale',
    published: true,
  },
  {
    id: 'don-ferrante',
    slug: 'don-ferrante',
    name: 'Don Ferrante',
    destination: 'Puglia',
    destinationSlug: 'puglia',
    destinationHref: '/destinazioni/italia',
    country: 'Italia',
    region: 'Puglia',
    category: 'Dimora sul mare',
    image:
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/hotel/it/don-ferrante.it.html',
    priceHint: 'EUR 290',
    rating: 9.3,
    summary:
      'Una scelta molto forte per chi vuole stare dentro il borgo e avere il mare come presenza continua, senza uscire dal contesto.',
    fit: 'Ottimo per city break di coppia e soggiorni brevi in cui la posizione conta quasi piu della metratura.',
    idealFor: ['romantic', 'town stay', 'sea view'],
    pros: ['Posizione fortissima', 'Molto scenografico', 'Perfetto per 2 notti'],
    cons: ['Meno privacy di una masseria', 'Puo essere piu esposto al flusso turistico'],
    editorialNote:
      'Lo scegliamo per il mix tra vista, pietra e accesso immediato al luogo, non per una vacanza di isolamento.',
    relatedGuideHref: '/guide?cat=dove-dormire',
    mapLabel: 'Monopoli',
    published: true,
  },
  {
    id: 'parilio',
    slug: 'parilio',
    name: 'Parilio, a Member of Design Hotels',
    destination: 'Grecia delle isole',
    destinationSlug: 'grecia-delle-isole',
    destinationHref: '/destinazioni/grecia',
    country: 'Grecia',
    region: 'Paros',
    category: 'Minimalismo bianco',
    image:
      'https://images.unsplash.com/photo-1505142468610-359e7d316be0?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/hotel/gr/parilio-a-member-of-design-hotels.it.html',
    priceHint: 'EUR 550',
    rating: 9.5,
    badge: 'Nostra scelta',
    summary:
      'Una scelta molto centrata sul lato design delle Cicladi: pulita, calda, non urlata e con una forte coerenza di atmosfera.',
    fit: 'Da scegliere se vuoi Grecia premium ma senza il look piu stereotipato da cartolina rumorosa.',
    idealFor: ['design', 'Cyclades', 'honeymoon', 'quiet luxury'],
    pros: ['Design molto coerente', 'Atmosfera calma', 'Forte identita'],
    cons: ['Prezzo alto', 'Serve allineamento col tono del viaggio'],
    editorialNote:
      'Paros qui funziona se vuoi una Grecia piu raffinata e meno ovvia. Il valore e nel tono complessivo, non solo nella camera.',
    relatedGuideHref: '/destinazioni/grecia',
    mapLabel: 'Paros',
    published: true,
  },
  {
    id: 'canaves-oia-suites',
    slug: 'canaves-oia-suites',
    name: 'Canaves Oia Suites',
    destination: 'Grecia delle isole',
    destinationSlug: 'grecia-delle-isole',
    destinationHref: '/destinazioni/grecia',
    country: 'Grecia',
    region: 'Santorini',
    category: 'Vista caldera',
    image:
      'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/hotel/gr/canaves-oia.it.html',
    priceHint: 'EUR 780',
    rating: 9.4,
    summary:
      'Una scelta iconica, da tenere per viaggi speciali in cui la vista e una parte sostanziale dell esperienza.',
    fit: 'Ha senso per honeymoon, anniversari o soggiorni brevi ad alto budget.',
    idealFor: ['honeymoon', 'Santorini', 'iconic stay'],
    pros: ['Vista fortissima', 'Servizio coerente', 'Altissima desiderabilita'],
    cons: ['Prezzo molto alto', 'Santorini richiede aspettative realistiche sul contesto'],
    editorialNote:
      'Lo consigliamo solo se vuoi davvero il lato iconico di Santorini e lo accetti con lucidita, non per un viaggio leggero di isola in isola.',
    relatedGuideHref: '/destinazioni/grecia',
    mapLabel: 'Oia',
    published: true,
  },
  {
    id: 'sao-lourenco-do-barrocal',
    slug: 'sao-lourenco-do-barrocal',
    name: 'Sao Lourenco do Barrocal',
    destination: 'Portogallo',
    destinationSlug: 'portogallo',
    destinationHref: '/destinazioni/portogallo',
    country: 'Portogallo',
    region: 'Alentejo',
    category: 'Tenuta storica',
    image:
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/hotel/pt/sao-lourenco-do-barrocal.it.html',
    priceHint: 'EUR 380',
    rating: 9.6,
    badge: 'Nostra scelta',
    summary:
      'Una delle strutture piu convincenti per capire l Alentejo con un taglio contemporaneo ma non artificiale.',
    fit: 'Ottima se il viaggio in Portogallo punta su ritmo lento, vino, luce e paesaggio rurale.',
    idealFor: ['slow travel', 'Portugal', 'design', 'wine trips'],
    pros: [
      'Identita molto forte',
      'Coerenza totale tra luogo e ospitalita',
      'Ottimo punto di fuga',
    ],
    cons: ['Richiede tempo', 'Meno adatta a viaggio urbano veloce'],
    editorialNote:
      'Qui il valore non e la checklist di servizi ma il modo in cui il luogo ti fa rallentare senza annoiarti.',
    relatedGuideHref: '/destinazioni/portogallo',
    mapLabel: 'Monsaraz',
    published: true,
  },
  {
    id: 'rosa-alpina-san-cassiano',
    slug: 'rosa-alpina-san-cassiano',
    name: 'Rosa Alpina Hotel & Spa',
    destination: 'Dolomiti',
    destinationSlug: 'dolomiti',
    destinationHref: '/destinazioni/italia',
    country: 'Italia',
    region: 'Alto Adige',
    area: 'Alta Badia',
    category: 'Relais storico di montagna',
    image:
      'https://images.unsplash.com/photo-1508615070457-7baeba4003ab?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/searchresults.html?ss=Rosa+Alpina+San+Cassiano',
    priceHint: 'EUR 520',
    budgetBand: 'Alto',
    rating: 9.5,
    badge: 'Nostra scelta',
    summary:
      'Relais & Chateaux storico in Alta Badia ridisegnato nel 2022. Stube ladina, tre stelle Michelin al St. Hubertus, biblioteca dove si resta mezza giornata.',
    fit: 'Per settimana bianca o autunno foliage in coppia, quando vuoi che la sera valga quanto il giorno.',
    idealFor: ['coppie', 'gastronomia', 'foliage', 'wellness'],
    pros: [
      'Architettura coerente col larice originale del 1960',
      'Ristorazione ai massimi livelli sia formale che stube',
      'Biblioteca e lounge pensati per il tempo lento',
    ],
    cons: ['Atmosfera formale che puo non piacere a tutti', 'Dress code cena non trascurabile'],
    editorialNote:
      'La stube serve knodel fatti a mano: non serve puntare al tre stelle per mangiare bene qui.',
    relatedGuideHref: '/guide/dolomiti-rifugi-design',
    mapLabel: 'San Cassiano / Alta Badia',
    published: true,
  },
  {
    id: 'lerchners-in-runggen',
    slug: 'lerchners-in-runggen',
    name: "Lerchner's in Runggen",
    destination: 'Dolomiti',
    destinationSlug: 'dolomiti',
    destinationHref: '/destinazioni/italia',
    country: 'Italia',
    region: 'Alto Adige',
    area: 'Val Pusteria',
    category: 'Cascina storica ridisegnata',
    image:
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/searchresults.html?ss=Lerchners+in+Runggen',
    priceHint: 'EUR 260',
    budgetBand: 'Medio',
    rating: 9.3,
    badge: 'Autentico',
    summary:
      'Cinque appartamenti ricavati in una cascina di Val Pusteria, ristorante da 30 coperti solo a cena. Materia prima del contadino, menu di due piatti.',
    fit: 'Per chi cerca autenticita vera, senza spa e senza servizi h24. Primavera e ottobre le stagioni migliori.',
    idealFor: ['coppie', 'famiglie', 'slow travel', 'food autentico'],
    pros: [
      'Gestione familiare senza filtri',
      'Ristorante che definisce la giornata',
      'Appartamenti completi con cucina',
    ],
    cons: ['Niente reception h24', 'Prenotato da mesi in alta stagione'],
    editorialNote:
      'La torta di grano saraceno della nonna di Josef resta per noi una delle colazioni migliori delle Alpi.',
    relatedGuideHref: '/guide/dolomiti-rifugi-design',
    mapLabel: 'Val Pusteria',
    published: true,
  },
  {
    id: 'utia-de-borz',
    slug: 'utia-de-borz',
    name: 'Utia de Borz',
    destination: 'Dolomiti',
    destinationSlug: 'dolomiti',
    destinationHref: '/destinazioni/italia',
    country: 'Italia',
    region: 'Alto Adige',
    area: 'Passo delle Erbe',
    category: 'Utia ladina rinnovata',
    image:
      'https://images.unsplash.com/photo-1551633863-6c89bcba5ad4?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/searchresults.html?ss=Utia+de+Borz+Passo+delle+Erbe',
    priceHint: 'EUR 160',
    budgetBand: 'Medio',
    rating: 9.1,
    badge: 'Per hiker veri',
    summary:
      'Rifugio di famiglia Rabanser al Passo delle Erbe, 1996 m. Sei camere affacciate sui Sass de Putia, punto di partenza del giro Puez-Odle.',
    fit: 'Per chi fa trekking reale e vuole dormire al punto di partenza. Chiude novembre-maggio.',
    idealFor: ['hiker', 'coppie attive', 'natura', 'stufe a legna'],
    pros: [
      'Muri portanti originali 1952 mantenuti',
      'Territorio ladino autentico con Torggelen ottobre',
      'Prezzo onesto per quota e posizione',
    ],
    cons: ['Accesso chiuso in inverno', 'Servizi base, niente spa'],
    editorialNote:
      'La stufa in ceramica alta due metri davanti al camino: vale piu di molte spa viste a quote piu basse.',
    relatedGuideHref: '/guide/dolomiti-rifugi-design',
    mapLabel: 'Passo delle Erbe',
    published: true,
  },
  {
    id: 'rifugio-lagazuoi',
    slug: 'rifugio-lagazuoi',
    name: 'Rifugio Lagazuoi',
    destination: 'Dolomiti',
    destinationSlug: 'dolomiti',
    destinationHref: '/destinazioni/italia',
    country: 'Italia',
    region: 'Veneto',
    area: 'Passo Falzarego',
    category: 'Rifugio alta quota',
    image:
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://rifugiolagazuoi.com',
    priceHint: 'EUR 95',
    budgetBand: 'Economico',
    rating: 9.0,
    badge: 'Esperienza una volta nella vita',
    summary:
      'Rifugio a 2752 m al Passo Falzarego, raggiungibile in funivia o a piedi. Vista aperta su Marmolada, Civetta, Tofane e le trincee della prima guerra.',
    fit: 'Almeno una notte nella vita, meglio con luna piena di giugno o settembre. Non un hotel: aspettative da calibrare.',
    idealFor: ['hiker', 'fotografi', 'alpinismo leggero', 'alba panoramica'],
    pros: [
      'Panorama 360 sui massicci piu iconici',
      'Terrazza al tramonto come ritrovo alpinismo europeo',
      'Prezzo accessibile per dormire sopra 2700 m',
    ],
    cons: ['Servizio base, doccia condivisa', 'Si prenota con 2-3 mesi di anticipo in estate'],
    editorialNote:
      'Alle 5:30 del mattino il ghiaccio sui vetri e la Marmolada rosa: non si dimentica.',
    relatedGuideHref: '/guide/dolomiti-rifugi-design',
    mapLabel: 'Passo Falzarego',
    published: true,
  },
  {
    id: 'masseria-cervarolo',
    slug: 'masseria-cervarolo',
    name: 'Masseria Cervarolo',
    destination: 'Puglia',
    destinationSlug: 'puglia',
    destinationHref: '/destinazioni/italia',
    country: 'Italia',
    region: 'Puglia',
    area: 'Valle d Itria',
    category: 'Masseria storica Relais',
    image:
      'https://images.unsplash.com/photo-1568495248636-6432b97bd949?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/searchresults.html?ss=Masseria+Cervarolo+Ostuni',
    priceHint: 'EUR 340',
    budgetBand: 'Alto',
    rating: 9.3,
    summary:
      'Masseria del XVII secolo ridisegnata come Relais. Volte a stella, piscina in pietra, orto biologico che rifornisce il ristorante.',
    fit: 'Base lenta per esplorare Valle d Itria con auto. Non isolata al punto da perdersi, non in paese.',
    idealFor: ['coppie', 'famiglie', 'gastronomia', 'architettura storica'],
    pros: [
      'Equilibrio tra storia e comfort senza disneyficazione',
      'Colazione nella ex-stalla restaurata',
      'Orto e vigna sul posto',
    ],
    cons: ['Isolata, serve auto per tutto', 'Pieno centro in alta stagione'],
    editorialNote:
      'La masseria che cambiamo idea tutte le volte: storica ma non museo, moderna ma non anonima.',
    relatedGuideHref: '/guide/puglia-roadtrip-borghi-bianchi',
    mapLabel: 'Valle d Itria / Ostuni',
    published: true,
  },
  {
    id: 'palazzo-bozzi-corso',
    slug: 'palazzo-bozzi-corso',
    name: 'Palazzo Bozzi Corso',
    destination: 'Puglia',
    destinationSlug: 'puglia',
    destinationHref: '/destinazioni/italia',
    country: 'Italia',
    region: 'Puglia',
    area: 'Lecce',
    category: 'Boutique barocco',
    image:
      'https://images.unsplash.com/photo-1548018560-c7196548e84d?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/searchresults.html?ss=Palazzo+Bozzi+Corso+Lecce',
    priceHint: 'EUR 440',
    budgetBand: 'Alto',
    rating: 9.4,
    badge: 'Nostra scelta',
    summary:
      'Otto suite nel palazzo nobiliare 1771 del centro barocco di Lecce. Spa nel seminterrato voltato, ristorante-terrazza sui tetti, ristoranti veri a 200 metri.',
    fit: 'Per vivere Lecce dentro, non da periferia. Coppie, weekend culturali, fuga gastronomica.',
    idealFor: ['coppie', 'arte barocca', 'food', 'city break'],
    pros: [
      'Posizione imbattibile nel barocco leccese',
      'Spa voltata atmosferica',
      'Terrazza sui tetti al tramonto',
    ],
    cons: ['Niente parcheggio privato', 'ZTL da gestire a arrivo'],
    editorialNote:
      'Il modo per capire Lecce senza fare navette continue: esci la mattina a piedi, rientri per siesta, riparti.',
    relatedGuideHref: '/guide/puglia-roadtrip-borghi-bianchi',
    mapLabel: 'Lecce centro',
    published: true,
  },
  {
    id: 'masseria-le-stanzie',
    slug: 'masseria-le-stanzie',
    name: 'Masseria Le Stanzie',
    destination: 'Puglia',
    destinationSlug: 'puglia',
    destinationHref: '/destinazioni/italia',
    country: 'Italia',
    region: 'Puglia',
    area: 'Salento profondo',
    category: 'Agriturismo di famiglia',
    image:
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/searchresults.html?ss=Masseria+Le+Stanzie+Supersano',
    priceHint: 'EUR 180',
    budgetBand: 'Medio',
    rating: 9.2,
    badge: 'Autentico',
    summary:
      'Otto camere in agriturismo di famiglia a Supersano, uliveto secolare, cucina 100% materia prima loro. Non lusso — autenticita.',
    fit: 'Antidoto alle masserie-hotel generiche del Salento. Per chi mette la tavola al centro.',
    idealFor: ['famiglie', 'food autentico', 'slow travel', 'budget consapevole'],
    pros: [
      'Pranzo domenicale con abitanti del paese',
      'Uliveto e forno visibili al giorno',
      'Prezzo onesto per qualita offerta',
    ],
    cons: ['Niente spa o piscina resort-style', 'Posizione rurale, serve auto'],
    editorialNote:
      'La domenica al loro tavolo ti fa capire la Puglia reale piu di 10 aperitivi sulla costa.',
    relatedGuideHref: '/guide/puglia-roadtrip-borghi-bianchi',
    mapLabel: 'Supersano',
    published: true,
  },
  {
    id: 'trulli-soave-alberobello',
    slug: 'trulli-soave-alberobello',
    name: 'Trulli Soave',
    destination: 'Puglia',
    destinationSlug: 'puglia',
    destinationHref: '/destinazioni/italia',
    country: 'Italia',
    region: 'Puglia',
    area: 'Alberobello',
    category: 'Trulli autentici',
    image:
      'https://images.unsplash.com/photo-1578302758063-0ef3e048df70?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/searchresults.html?ss=Trulli+Soave+Alberobello',
    priceHint: 'EUR 220',
    budgetBand: 'Medio',
    rating: 9.0,
    summary:
      'Tre trulli autentici ristrutturati (non ricostruiti) nel Rione Aia Piccola — la zona meno turistica di Alberobello. Gestione familiare, dolci fatti in casa.',
    fit: 'Per vivere un trullo vero senza la trappola di Rione Monti iper-affollato. Coppie o piccole famiglie.',
    idealFor: ['coppie', 'famiglie piccole', 'autenticita', 'weekend'],
    pros: ['Trulli storici non ricostruiti', 'Rione meno turistico', 'Colazione homemade'],
    cons: ['Tre unita distinte: gruppi 6+ meno pratico', 'Parcheggio fuori ZTL Monti'],
    editorialNote: 'Il modo per dormire in un trullo senza sentirsi in un parco a tema.',
    relatedGuideHref: '/guide/puglia-roadtrip-borghi-bianchi',
    mapLabel: 'Alberobello / Aia Piccola',
    published: true,
  },
  {
    id: 'hotel-budir',
    slug: 'hotel-budir',
    name: 'Hotel Budir',
    destination: 'Islanda',
    destinationSlug: 'islanda',
    destinationHref: '/destinazioni/islanda',
    country: 'Islanda',
    region: 'Snaefellsnes',
    category: 'Hotel iconico minimale',
    image:
      'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/searchresults.html?ss=Hotel+Budir+Iceland',
    priceHint: 'EUR 330',
    budgetBand: 'Alto',
    rating: 9.2,
    badge: 'Nostra scelta',
    summary:
      'L hotel piu iconico d Islanda. Solitario sulla costa nera di Snaefellsnes, chiesetta di legno 1703 a 100 metri, sala lettura con camino di pietra.',
    fit: 'La prima notte o l ultima della Ring Road, quando vuoi un luogo che sia gia paesaggio.',
    idealFor: ['coppie', 'fotografi', 'viaggi lenti', 'inverno'],
    pros: [
      'Posizione solitaria e iconica',
      'Architettura nordica minimale coerente',
      'Sala lettura perfetta per notti di tempesta',
    ],
    cons: ['Lontano da altri servizi', 'Ristorante con orari fissi'],
    editorialNote:
      'Se esiste un hotel "Islanda in una foto", e questo. Prezzi invernali piu accessibili.',
    relatedGuideHref: '/guide/islanda-ring-road-inverno',
    mapLabel: 'Snaefellsnes',
    published: true,
  },
  {
    id: 'fosshotel-glacier-lagoon',
    slug: 'fosshotel-glacier-lagoon',
    name: 'Fosshotel Glacier Lagoon',
    destination: 'Islanda',
    destinationSlug: 'islanda',
    destinationHref: '/destinazioni/islanda',
    country: 'Islanda',
    region: 'Costa sud-est',
    area: 'Hof',
    category: 'Hotel strategico glacier',
    image:
      'https://images.unsplash.com/photo-1500520198921-6d4704f98092?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/searchresults.html?ss=Fosshotel+Glacier+Lagoon',
    priceHint: 'EUR 270',
    budgetBand: 'Alto',
    rating: 8.7,
    summary:
      'A 25 minuti dalla laguna Jokulsarlon. Architettura industriale, non romantica — ma la posizione per aurora hunting e icebergs vale oro.',
    fit: 'Per chi mette la logistica davanti alla forma. Base strategica per il tratto piu scenografico della Ring Road.',
    idealFor: ['aurora hunters', 'fotografi', 'viaggi inverno', 'logistica'],
    pros: [
      'Posizione imbattibile per Jokulsarlon e Diamond Beach',
      '30 minuti dal ghiacciaio Vatnajokull al buio',
      'Stanze riscaldate bene per inverno artico',
    ],
    cons: ['Estetica industriale, non romantica', 'Ristorante base, meglio cenare a Hofn'],
    editorialNote: 'La scegliamo per pragmatismo: quando la logistica vince sulla foto dell hotel.',
    relatedGuideHref: '/guide/islanda-ring-road-inverno',
    mapLabel: 'Hof / Jokulsarlon',
    published: true,
  },
  {
    id: 'vogafjos-farm-resort',
    slug: 'vogafjos-farm-resort',
    name: 'Vogafjos Farm Resort',
    destination: 'Islanda',
    destinationSlug: 'islanda',
    destinationHref: '/destinazioni/islanda',
    country: 'Islanda',
    region: 'Nord',
    area: 'Myvatn',
    category: 'Fattoria con cottage',
    image:
      'https://images.unsplash.com/photo-1518708950060-2a6c193fae47?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/searchresults.html?ss=Vogafjos+Farm+Resort',
    priceHint: 'EUR 240',
    budgetBand: 'Medio',
    rating: 9.1,
    badge: 'Autentico',
    summary:
      'Fattoria-hotel ancora in attivita vicino al lago Myvatn. Cottage moderni con vista lago, colazione con latte della loro stalla, trota affumicata del Laxa.',
    fit: 'L esperienza farm-to-table piu reale d Islanda. Base perfetta per Myvatn e Godafoss.',
    idealFor: ['famiglie', 'slow travel', 'food autentico', 'natura'],
    pros: [
      'Stalla visibile dalle vetrate del ristorante',
      'Cottage ben isolati per inverno',
      'Accesso facile a Nature Baths e Godafoss',
    ],
    cons: ['Ristorante prenotato spesso, prenotare cena all arrivo', 'Traffico pesante d estate'],
    editorialNote:
      'La stalla visibile dal ristorante non e un difetto: e la ragione per cui mangi quel latte.',
    relatedGuideHref: '/guide/islanda-ring-road-inverno',
    mapLabel: 'Myvatn',
    published: true,
  },
  {
    id: 'hotel-kria-vik',
    slug: 'hotel-kria-vik',
    name: 'Hotel Kria',
    destination: 'Islanda',
    destinationSlug: 'islanda',
    destinationHref: '/destinazioni/islanda',
    country: 'Islanda',
    region: 'Costa sud',
    area: 'Vik',
    category: 'Design scandinavo contemporaneo',
    image:
      'https://images.unsplash.com/photo-1531219572328-a0171b4448a3?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/searchresults.html?ss=Hotel+Kria+Vik',
    priceHint: 'EUR 280',
    budgetBand: 'Alto',
    rating: 9.0,
    summary:
      'Aperto 2021 nel paese piu a sud dell isola. Legno nero, vetri full-height, camere con vista su Reynisfjara in distanza. Sauna finlandese panoramica.',
    fit: 'Base ideale per i 3 giorni del sud: Skaftafell, Diamond Beach, canyon Fjadrargljufur. Architettura che non distrae.',
    idealFor: ['coppie', 'fotografi', 'design lover', 'ring road base sud'],
    pros: [
      'Architettura scandinava pulita e coerente',
      'Sauna con vista panoramica',
      'Centro Vik a piedi per cene',
    ],
    cons: ['Area spa limitata', 'Vik d estate puo essere caotico'],
    editorialNote:
      'L unico hotel nel sud Islanda con estetica davvero contemporanea. Se cerchi carattere senza rustic, e qui.',
    relatedGuideHref: '/guide/islanda-ring-road-inverno',
    mapLabel: 'Vik',
    published: true,
  },
  {
    id: 'konsulat-reykjavik',
    slug: 'konsulat-reykjavik',
    name: 'Konsulat Hotel',
    destination: 'Islanda',
    destinationSlug: 'islanda',
    destinationHref: '/destinazioni/islanda',
    country: 'Islanda',
    region: 'Capitale',
    area: 'Reykjavik',
    category: 'Boutique storico urbano',
    image:
      'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?q=80&w=1600&auto=format&fit=crop',
    bookingUrl: 'https://www.booking.com/searchresults.html?ss=Konsulat+Hotel+Reykjavik',
    priceHint: 'EUR 250',
    budgetBand: 'Medio',
    rating: 9.0,
    summary:
      'Nel quartiere Laugavegur, palazzina storica ristrutturata 2020. Pavimenti in legno originali, caffetteria al piano terra dove vanno davvero i locali.',
    fit: 'Per la prima o l ultima notte della Ring Road — capitale vissuta bene, non da turista.',
    idealFor: ['city break', 'coppie', 'viaggiatori indipendenti'],
    pros: [
      'Posizione centrale a piedi dal Harpa',
      'Caffetteria frequentata dai locali',
      'Camere diverse, non cookie-cutter',
    ],
    cons: ['Parcheggio pubblico a 300 m', 'Nessun parcheggio privato gratis (tipico Reykjavik)'],
    editorialNote:
      'La prima notte meglio qui che al Blue Lagoon Hotel: entri nella citta invece che nel resort.',
    relatedGuideHref: '/guide/islanda-ring-road-inverno',
    mapLabel: 'Reykjavik centro',
    published: true,
  },
];

export function getPublishedHotels() {
  return HOTEL_DIRECTORY.filter((hotel) => hotel.published !== false);
}

export function getHotelBySlug(slug: string) {
  return getPublishedHotels().find((hotel) => hotel.slug === slug) ?? null;
}

export function getHotelsByDestination() {
  return getPublishedHotels().reduce<Record<string, HotelEntry[]>>((groups, hotel) => {
    if (!groups[hotel.destination]) {
      groups[hotel.destination] = [];
    }
    groups[hotel.destination].push(hotel);
    return groups;
  }, {});
}
