/**
 * Reel manifest — single source of truth per i reel Instagram/TikTok di
 * Rodrigo & Betta integrati nel sito.
 *
 * Consumato da:
 *  - `HeroSection.tsx` → FEATURED_REEL fallback dinamico (sceglie il reel
 *    con più views se manifest popolato, altrimenti fallback editoriale).
 *  - `InstagramGrid.tsx` → render delle cover come grid masonry.
 *  - `Esplora.tsx` (futuro) → anchor visivo contestuale quando l'utente
 *    filtra `?zone=X` e c'è un reel `zone === X` disponibile.
 *
 * TODO[R+B]: compilare ogni entry con i metadati reali del post pubblicato.
 * Finché `caption`, `instagramUrl` o `cover` restano vuoti, il manifest è
 * marcato come `isPlaceholder: true` e il consumer applica fallback editoriale.
 *
 * I 5 file MP4 sono in `/public/video/` (originali in `C:\...\video\`).
 * Per servirli dal browser vanno copiati/linkati in `/public/video/`.
 */

import type { ContentType, Zone } from './contentTaxonomy';
import { resolveVideoUrl } from '../utils/mediaUrl';

export interface ReelEntry {
  /** ID stabile per analytics e routing (es. "salento-agosto-2025"). */
  id: string;
  /** Path locale relativo a `/public/`. */
  localPath: string;
  /** Cover statica per browser preview / lazy load (webp consigliato). */
  cover: string;
  /** Alt text IT della cover: descrive la scena visibile, non l'hook. */
  alt: string;
  /** Localita' descrittiva (es. "Salento · Spiaggia di Pescoluse"). */
  location: string;
  /** Zona canonical (per filtraggio in /esplora). */
  zone: Zone;
  /** Tipo canonical primario del reel (per filtraggio in /esplora). */
  type: ContentType;
  /** Caption completa del post Instagram/TikTok. */
  caption: string;
  /** Prima frase di hook (primi 60-80 caratteri della caption). */
  hook: string;
  /** Hashtag senza '#'. */
  hashtags: string[];
  /** URL pubblico del post Instagram (https://instagram.com/p/...). */
  instagramUrl?: string;
  /**
   * Mostra il video dentro il sito invece di mandare su Instagram.
   *
   * Il comportamento normale e' l'anteprima: copertina verticale con il play,
   * il tocco apre il reel su Instagram. Serve perche' i 533 posti in arrivo un
   * video locale non ce l'hanno e non lo avranno, e perche' `public/video/` e'
   * gitignored: quei file non entrano nel build della CI.
   *
   * Con questo acceso il tocco monta il `<video>` in pagina — sempre al tocco,
   * mai da solo — e il link a Instagram resta sotto. Ha senso solo dove
   * `localPath` punta a un file davvero raggiungibile: in produzione significa
   * `VITE_VIDEO_BASE_URL` configurata.
   */
  videoInPagina?: boolean;
  /** URL pubblico del post TikTok (https://tiktok.com/@.../video/...). */
  tiktokUrl?: string;
  /** Id del posto corrispondente in content-seed (per il deep link
   *  reel → /posto/:slug dal bio hub). Assente = nessuna scheda ancora. */
  postoId?: string;
  /** Views totali (Instagram + TikTok aggregato), se note. */
  views?: number;
  /** ISO date di pubblicazione. */
  publishedAt: string;
  /** True finché i metadati sono placeholder TODO[R+B]. */
  isPlaceholder: boolean;
}

/**
 * 5 reel LIVE — corrispondono ai 5 file MP4 in `public/video/`.
 *
 * Cover = frame reali estratti dai video con ffmpeg (2026-06-18), salvati in
 * `public/images/reels/reel-N-cover.webp`. Le vecchie cover stock placeholder
 * sono in `backups/ultracode-2026-06-18/old-reel-covers/`.
 *
 * Metadata (location/zone/type/caption/hook) derivati dal contenuto REALE dei
 * video. Mancano ancora `instagramUrl`/`tiktokUrl`/`views` per ciascun post: il
 * consumer usa il fallback al profilo IG finché R+B non li fornisce.
 */
const RAW_REELS: ReelEntry[] = [
  {
    id: 'reel-novara-emotional-grand-motel',
    localPath: '/video/novara-emotional-grand-motel.mp4',
    cover: '/images/reels/novara-emotional-grand-motel-cover.webp',
    alt: "Camera a tema con letto rotondo dentro una gabbia dorata e pareti rosse dell'Emotional Grand Motel.",
    location: 'Novara · Emotional Grand Motel',
    zone: 'Italia',
    type: 'Hotel con carattere',
    caption:
      'Motel a tema vicino Novara: abbiamo provato la stanza “Celebrity”, con letto dentro una gabbia dorata e vasca particolare. Colazione in camera o a buffet. Il prezzo varia in base alla stanza e alla permanenza. Per chi vuole una notte fuori dagli schemi.',
    hook: 'Dormiresti in una gabbia?',
    hashtags: ['suitetematica', 'postiparticolari', 'visitnovara', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/C_-a3IUoNL4/',
    postoId: 'novara-emotional-grand-motel',
    publishedAt: '2024-09-16',
    isPlaceholder: false,
  },
  {
    id: 'reel-rust-rulantica-waterpark',
    localPath: '/video/rust-rulantica-waterpark.mp4',
    cover: '/images/reels/rust-rulantica-waterpark-cover.webp',
    alt: 'Interni a tema nordico del parco acquatico coperto Rulantica con scivoli e piscine.',
    location: 'Rust · Rulantica',
    zone: 'Europa',
    type: 'Posti particolari',
    caption:
      "Parco acquatico interamente al coperto a Rust, in Germania, accanto a Europa-Park: oltre 17 attrazioni per tutti, tra cui uno degli scivoli più veloci d'Europa, scivoli con gommone e piscina a onde. Ambientazione a tema nordico. Se vieni qui, vale la pena abbinare anche Europa-Park.",
    hook: 'Uno degli acquapark più divertenti al mondo?',
    hashtags: ['rulantica', 'europapark', 'acquapark', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DBRWYD9ogMn/',
    postoId: 'rust-rulantica-waterpark',
    publishedAt: '2024-10-18',
    isPlaceholder: false,
  },
  {
    id: 'reel-sirmione-hotel-lugana-parco',
    localPath: '/video/sirmione-hotel-lugana-parco.mp4',
    cover: '/images/reels/sirmione-hotel-lugana-parco-cover.webp',
    alt: "Parco privato sul Lago di Garda con piscina e pontile dell'Hotel Lugana Parco al Lago.",
    location: 'Sirmione · Hotel Lugana Parco al Lago & Wine Hotel',
    zone: 'Italia',
    type: 'Hotel con carattere',
    caption:
      "Hotel di design a due passi da Sirmione: camere curate nei dettagli, bottiglia di benvenuto della cantina Ca' dei Frati, parco privato sul lago con piscina e pontile, e ristorante del territorio. Su richiesta si organizza una visita privata in cantina. Per una fuga di coppia tra vino e relax.",
    hook: 'Un weekend romantico sul Lago di Garda?',
    hashtags: ['lagodigarda', 'sirmione', 'weekendromantico', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DbKdcluM13G/',
    postoId: 'sirmione-hotel-lugana-parco',
    publishedAt: '2026-07-24',
    isPlaceholder: false,
  },
  {
    id: 'reel-iseo-flyboard-pisogne',
    localPath: '/video/iseo-flyboard-pisogne.mp4',
    cover: '/images/reels/iseo-flyboard-pisogne-cover.webp',
    alt: "Persona che si libra sull'acqua con un flyboard sul Lago d'Iseo.",
    location: 'Pisogne · Flyboard Cam1 · X Beach',
    zone: 'Italia',
    type: 'Insolito',
    caption:
      "Esperienza di flyboard sul Lago d'Iseo, alla X Beach di Pisogne: la sessione dura 40 minuti, di cui circa 20 di volo effettivo, sufficienti per iniziare a fare evoluzioni. Costo 130€. Adrenalina pura, con qualche tuffo assicurato. Per chi cerca un'esperienza fuori dal comune.",
    hook: "Voleresti sull'acqua?",
    hashtags: ['lagodiiseo', 'flyboard', 'esperienze', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DbCvtnksPBy/',
    postoId: 'iseo-flyboard-pisogne',
    publishedAt: '2026-07-21',
    isPlaceholder: false,
  },
  {
    id: 'reel-como-haru-sushi',
    localPath: '/video/como-haru-sushi.mp4',
    cover: '/images/reels/como-haru-sushi-cover.webp',
    alt: 'Sala intima del ristorante Haru Sushi a Como con tavoli riservati.',
    location: 'Como · Haru Sushi',
    zone: 'Italia',
    type: 'Food & Ristoranti',
    caption:
      'Ristorante di sushi a Como, piccolo e intimo, con tavoli riservati per pranzo o cena in tranquillità. Menù all you can eat con pesce di buona qualità e tante proposte. Pranzo a partire da 16€, cena da 28€.',
    hook: 'Un sushi a forma di alveare?',
    hashtags: ['comofood', 'sushi', 'ristoranti', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/Da7SLwRMrjM/',
    postoId: 'como-haru-sushi',
    publishedAt: '2026-07-18',
    isPlaceholder: false,
  },
  {
    id: 'reel-lazise-movieland-caneva',
    localPath: '/video/lazise-movieland-caneva.mp4',
    cover: '/images/reels/lazise-movieland-caneva-cover.webp',
    alt: 'Attrazioni acquatiche e scivoli del Caneva Aquapark a Lazise.',
    location: 'Lazise · Movieland Park & Caneva Aquapark',
    zone: 'Italia',
    type: 'Posti particolari',
    caption:
      "Due parchi in una sola giornata a Lazise, sul Lago di Garda: Movieland per adrenalina, spettacoli e attrazioni a tema cinema, e Caneva Aquapark per scivoli, piscine e relax. Una combinazione pensata per le giornate afose d'estate.",
    hook: "I parchi perfetti per l'estate?",
    hashtags: ['lagodigarda', 'movieland', 'caneva', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DaxK1gHMv71/',
    postoId: 'lazise-movieland-caneva',
    publishedAt: '2026-07-14',
    isPlaceholder: false,
  },
  {
    id: 'reel-montepulciano-altro-cantuccio',
    localPath: '/video/montepulciano-altro-cantuccio.mp4',
    cover: '/images/reels/montepulciano-altro-cantuccio-cover.webp',
    alt: "Portata di un menù degustazione storico servita a L'Altro Cantuccio, Montepulciano.",
    location: "Montepulciano · L'Altro Cantuccio",
    zone: 'Italia',
    type: 'Food & Ristoranti',
    caption:
      "A Montepulciano, un menù degustazione di 8 portate che ripercorre la storia della città dall'antichità a oggi: ogni portata rappresenta un'epoca ed è preparata con ingredienti realmente usati in quel periodo. Esperienza di fine dining a 70€ a persona, con possibilità di abbinamento vini.",
    hook: 'Viaggiare nella storia mangiando?',
    hashtags: ['montepulciano', 'finedining', 'toscana', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DauuMM1Mkez/',
    postoId: 'montepulciano-altro-cantuccio',
    publishedAt: '2026-07-13',
    isPlaceholder: false,
  },
  {
    id: 'reel-ravenna-better-sushi',
    localPath: '/video/ravenna-better-sushi.mp4',
    cover: '/images/reels/ravenna-better-sushi-cover.webp',
    alt: "Ambiente scenografico con cascate e passerelle sull'acqua del ristorante Better Sushi a Ravenna.",
    location: 'Ravenna · Better Sushi',
    zone: 'Italia',
    type: 'Food & Ristoranti',
    caption:
      "Ristorante di sushi a Ravenna con ambienti scenografici tra cascate e passerelle sull'acqua. Menù all you can eat con piatti curati e ingredienti freschi. Pranzo da 14,90€, cena da 28,90€. Più di una cena: un'esperienza per chi ama il genere.",
    hook: 'Il sushi più bello della Romagna?',
    hashtags: ['ravenna', 'sushi', 'emiliaromagna', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DapaSgMMnyd/',
    postoId: 'ravenna-better-sushi',
    publishedAt: '2026-07-11',
    isPlaceholder: false,
  },
  {
    id: 'reel-sarteano-chiostro-cennini',
    localPath: '/video/sarteano-chiostro-cennini.mp4',
    cover: '/images/reels/sarteano-chiostro-cennini-cover.webp',
    alt: 'Tavoli apparecchiati nel chiostro quattrocentesco del ristorante Chiostro Cennini a Sarteano.',
    location: 'Sarteano · Chiostro Cennini',
    zone: 'Italia',
    type: 'Food & Ristoranti',
    caption:
      "Nel borgo di Sarteano, in provincia di Siena, un ristorante ricavato in un chiostro quattrocentesco. Si inizia con un aperitivo in altalena e prodotti di loro produzione, poi una cucina tipica rivisitata con menù stagionale. Ci si può fermare anche per il dopocena, immersi nell'atmosfera del chiostro.",
    hook: 'Ceneresti in un chiostro del XV secolo?',
    hashtags: ['sarteano', 'siena', 'toscana', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DafM3Totc-3/',
    postoId: 'sarteano-chiostro-cennini',
    publishedAt: '2026-07-07',
    isPlaceholder: false,
  },
  {
    id: 'reel-londra-warner-bros-studio-harry-potter',
    localPath: '/video/londra-warner-bros-studio-harry-potter.mp4',
    cover: '/images/reels/londra-warner-bros-studio-harry-potter-cover.webp',
    alt: 'Set originale del tour degli studi Warner Bros. di Harry Potter a Londra.',
    location: 'Londra · Warner Bros. Studio Tour London',
    zone: 'Europa',
    type: 'Posti particolari',
    caption:
      'Il tour degli studi Warner Bros. a Londra, dove è stato girato Harry Potter: set originali, costumi e oggetti di scena della saga. Una tappa per i fan, da rifare con calma. Prenotazione consigliata con anticipo.',
    hook: 'Credi nella magia?',
    hashtags: ['harrypotter', 'londra', 'warnerbros', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DaYSq2sMK6p/',
    postoId: 'londra-warner-bros-studio-harry-potter',
    publishedAt: '2026-07-04',
    isPlaceholder: false,
  },
  {
    id: 'reel-madrid-la-santoria',
    localPath: '/video/madrid-la-santoria.mp4',
    cover: '/images/reels/madrid-la-santoria-cover.webp',
    alt: 'Interni a tema santería del cocktail bar La Santoria a Madrid.',
    location: 'Madrid · La Santoria',
    zone: 'Europa',
    type: 'Insolito',
    caption:
      'Cocktail bar nascosto di Madrid ispirato al mondo della santería: drink a cui vengono attribuite proprietà portafortuna e lettura dei tarocchi. Un posto fuori dal comune, dove siamo tornati dopo la prima volta. Per chi cerca locali particolari.',
    hook: 'Un locale che ti toglie il malocchio?',
    hashtags: ['madrid', 'localimadrid', 'postiparticolari', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DaR3eMUMub1/',
    postoId: 'madrid-la-santoria',
    publishedAt: '2026-07-02',
    isPlaceholder: false,
  },
  {
    id: 'reel-asciano-casa-lavanda-podere-fossaccio',
    localPath: '/video/asciano-casa-lavanda-podere-fossaccio.mp4',
    cover: '/images/reels/asciano-casa-lavanda-podere-fossaccio-cover.webp',
    alt: 'Piscina a sfioro con vista sulle Crete Senesi di Casa Lavanda ad Asciano.',
    location: 'Asciano · Casa Lavanda — Podere Fossaccio',
    zone: 'Italia',
    type: 'Hotel con carattere',
    caption:
      'Appartamento in stile rustico toscano ad Asciano, nelle Crete Senesi: due camere matrimoniali, cucina attrezzata e piscina a sfioro con vista sulle colline. Il posto giusto per rallentare, per un weekend romantico o una fuga con gli amici.',
    hook: 'Dormiresti immerso nelle colline toscane?',
    hashtags: ['cretesenesi', 'toscana', 'podere', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DaPjh9ksq9_/',
    postoId: 'asciano-casa-lavanda-podere-fossaccio',
    publishedAt: '2026-07-01',
    isPlaceholder: false,
  },
  {
    id: 'reel-verona-casabarca',
    localPath: '/video/verona-casabarca.mp4',
    cover: '/images/reels/verona-casabarca-cover.webp',
    alt: 'Piatto ricoperto da una cascata di tartufo al ristorante CasaBarca di Verona.',
    location: 'Verona · CasaBarca',
    zone: 'Italia',
    type: 'Food & Ristoranti',
    caption:
      'A Verona, una location elegante e fuori dal comune: pizze farcite, piatti della tradizione veronese, un menù estivo con abbinamenti creativi e portate ricoperte da una vera cascata di tartufo. Da mettere in lista per un weekend in città.',
    hook: 'Una pioggia di tartufo?',
    hashtags: ['verona', 'tartufo', 'ristoranti', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DaMuAWCso-V/',
    postoId: 'verona-casabarca',
    publishedAt: '2026-06-30',
    isPlaceholder: false,
  },
  {
    id: 'reel-valeggio-parco-cavour',
    localPath: '/video/valeggio-parco-cavour.mp4',
    cover: '/images/reels/valeggio-parco-cavour-cover.webp',
    alt: 'Piscina tropicale con sabbia bianca Palm Beach del Parco Cavour a Valeggio sul Mincio.',
    location: 'Valeggio sul Mincio · Parco Cavour',
    zone: 'Italia',
    type: 'Posti particolari',
    caption:
      "Parco acquatico immerso nel verde a Valeggio sul Mincio: scivoli, giochi d'acqua e la Palm Beach, una piscina tropicale con sabbia bianca. C'è anche un'area wellness, le Terme Romane, tra cascate e idromassaggi. Per una giornata in famiglia.",
    hook: 'Un paradiso tropicale in Italia?',
    hashtags: ['valeggiosulmincio', 'acquapark', 'veneto', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DZ7r9JJMfgV/',
    postoId: 'valeggio-parco-cavour',
    publishedAt: '2026-06-23',
    isPlaceholder: false,
  },
  {
    id: 'reel-cancun-riu-messico',
    localPath: '/video/cancun-riu-messico.mp4',
    cover: '/images/reels/cancun-riu-messico-cover.webp',
    alt: 'Spiaggia caraibica dal mare turchese a Cancún, Messico.',
    location: 'Cancún · Riu Cancún',
    zone: 'Americhe',
    type: 'Relax, terme e spa',
    caption:
      "Due settimane a Cancún ad agosto, contro i luoghi comuni: caldo e sole quasi ogni giorno, mare caraibico e cenote. Il sargasso dipende molto dalle zone — al Riu Cancún ce n'era poco, anche per la pulizia costante. Sulla sicurezza: nelle zone turistiche, con buon senso, ci siamo sempre sentiti tranquilli.",
    hook: 'Agosto in Messico?',
    hashtags: ['cancun', 'messico', 'rivieramaya', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DZy-HunM8Rt/',
    postoId: 'cancun-riu-messico',
    publishedAt: '2026-06-20',
    isPlaceholder: false,
  },
  {
    id: 'reel-toscana-suite-spa-civico-4',
    localPath: '/video/toscana-suite-spa-civico-4.mp4',
    cover: '/images/reels/toscana-suite-spa-civico-4-cover.webp',
    alt: 'Suite privata con vasca idromassaggio e luci soffuse di Suite Spa Civico 4 in Toscana.',
    location: 'Toscana · Suite Spa Civico 4',
    zone: 'Italia',
    type: 'Hotel con carattere',
    caption:
      'Non un hotel tradizionale, ma una suite privata in Toscana pensata esclusivamente per due persone: sauna a infrarossi, vasca idromassaggio, doccia emozionale e cinema in camera con maxi schermo da 100”. Pacchetti romantici disponibili. Si parte da 190€ a notte (210€ nel weekend).',
    hook: 'Una suite privata con SPA solo per due?',
    hashtags: ['alloggiparticolari', 'toscana', 'weekendromantico', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DZwX5URsxZc/',
    postoId: 'toscana-suite-spa-civico-4',
    publishedAt: '2026-06-19',
    isPlaceholder: false,
  },
  {
    id: 'reel-lombardia-agriturismo-graffignana',
    localPath: '/video/lombardia-agriturismo-graffignana.mp4',
    cover: '/images/reels/lombardia-agriturismo-graffignana-cover.webp',
    alt: "Piscina e area verde dell'agriturismo Contea del Vignolo Fiorito a Graffignana.",
    location: 'Graffignana · Contea del Vignolo Fiorito',
    zone: 'Italia',
    type: 'Posti particolari',
    caption:
      'Agriturismo a Graffignana con tanti animali, molti salvati da situazioni difficili. Puoi passare la giornata in piscina (ingresso 40€, con lettino 50€, con pranzo a buffet o apericena) oppure fermarti a pranzo con prodotti genuini e stagionali.',
    hook: 'Un agriturismo con animali?',
    hashtags: [],
    instagramUrl: 'https://www.instagram.com/reel/DZscTqAshTD/',
    postoId: 'lombardia-agriturismo-graffignana',
    publishedAt: '2026-06-17',
    isPlaceholder: false,
  },
  {
    id: 'reel-verona-vigna-benini',
    localPath: '/video/verona-vigna-benini.mp4',
    cover: '/images/reels/verona-vigna-benini-cover.webp',
    alt: 'Tavoli tra i filari della vigna al tramonto, Alessandro Benini Wines a Lavagno.',
    location: 'Lavagno · Alessandro Benini Wines',
    zone: 'Italia',
    type: 'Food & Ristoranti',
    caption:
      'Aperitivo tra i filari a Lavagno, vicino Verona: vino prodotto dalla cantina, musica e tramonto. Con una bottiglia è incluso un tagliere di salumi, formaggi e taralli, a 28€.',
    hook: 'Un aperitivo in vigna?',
    hashtags: [],
    instagramUrl: 'https://www.instagram.com/reel/DZjvWDoslzS/',
    postoId: 'verona-vigna-benini',
    publishedAt: '2026-06-14',
    isPlaceholder: false,
  },
  {
    id: 'reel-chioggia-sand-beach',
    localPath: '/video/chioggia-sand-beach.mp4',
    cover: '/images/reels/chioggia-sand-beach-cover.webp',
    alt: 'Lido fronte mare con lettini del Sand Beach Club a Chioggia.',
    location: 'Chioggia · Sand Beach Club',
    zone: 'Italia',
    type: 'Relax, terme e spa',
    caption:
      'Giornata di mare a Chioggia: passeggiata nel centro storico, ostriche fresche al Do Ombre, e il Sand Beach Club — lido esclusivo fronte mare con pranzi, cene, eventi e gazebo vip.',
    hook: 'Una meta di mare sottovalutata?',
    hashtags: [],
    instagramUrl: 'https://www.instagram.com/reel/DZhFdM_sQY9/',
    postoId: 'chioggia-sand-beach',
    publishedAt: '2026-06-13',
    isPlaceholder: false,
  },
  {
    id: 'reel-jesolo-caribe-bay',
    localPath: '/video/jesolo-caribe-bay.mp4',
    cover: '/images/reels/jesolo-caribe-bay-cover.webp',
    alt: 'Sabbia bianca, palme e lagune del parco acquatico Caribe Bay a Jesolo.',
    location: 'Jesolo · Caribe Bay',
    zone: 'Italia',
    type: 'Insolito',
    caption:
      "Parco acquatico caraibico a Jesolo: 80.000 mq di sabbia bianca, palme e lagune, 25 attrazioni tra gli scivoli più adrenalinici d'Europa e il relax di Shark Bay, più 4 spettacoli giornalieri. Biglietto 39€, meno acquistando online.",
    hook: 'I Caraibi in Italia?',
    hashtags: [],
    instagramUrl: 'https://www.instagram.com/reel/DZaO32kMg8R/',
    postoId: 'jesolo-caribe-bay',
    publishedAt: '2026-06-10',
    isPlaceholder: false,
  },
  {
    id: 'reel-madrid-storyland-disney',
    localPath: '/video/madrid-storyland-disney.mp4',
    cover: '/images/reels/madrid-storyland-disney-cover.webp',
    alt: 'Sala a tema principesse del ristorante Storyland a Madrid.',
    location: 'Madrid · Storyland',
    zone: 'Europa',
    type: 'Insolito',
    caption:
      "Ristorante a tema principesse a Madrid: indossi un vestito ed entri nell'ambientazione ispirata ai cartoni, con piatti scenografici e specialità argentine. A metà cena inizia uno spettacolo con le principesse.",
    hook: 'Una cena nel mondo Disney?',
    hashtags: [],
    instagramUrl: 'https://www.instagram.com/reel/DZWo5OTM_Cw/',
    postoId: 'madrid-storyland-disney',
    publishedAt: '2026-06-09',
    isPlaceholder: false,
  },
  {
    id: 'reel-lombardia-al-mago-medievale',
    localPath: '/video/lombardia-al-mago-medievale.mp4',
    cover: '/images/reels/lombardia-al-mago-medievale-cover.webp',
    alt: 'Spettacolo di falconeria durante la cena al Ristorante Al Mago ad Albairate.',
    location: 'Albairate · Al Mago',
    zone: 'Italia',
    type: 'Insolito',
    caption:
      'Ristorante ad Albairate dove ceni assistendo a spettacoli di falconeria e arti medievali: esibizioni con falchi, gufi e rapaci, con momenti interattivi in cui provi a richiamarli in prima persona.',
    hook: 'Una locanda medievale con falconeria?',
    hashtags: [],
    instagramUrl: 'https://www.instagram.com/reel/DZPFeJBMF9v/',
    postoId: 'lombardia-al-mago-medievale',
    publishedAt: '2026-06-06',
    isPlaceholder: false,
  },
  {
    id: 'reel-capovaticano-tonicello-resort',
    localPath: '/video/capovaticano-tonicello-resort.mp4',
    cover: '/images/reels/capovaticano-tonicello-resort-cover.webp',
    alt: 'Vista sul mare cristallino della Costa degli Dei dal Tonicello Resort a Capo Vaticano.',
    location: 'Capo Vaticano · Tonicello Resort & Spa',
    zone: 'Italia',
    type: 'Hotel con carattere',
    caption:
      "Resort affacciato sulla Costa degli Dei, a Capo Vaticano: acque cristalline, calette e tramonti, con terrazza panoramica del ristorante sul mare. A un'ora di volo, i 'Caraibi d'Italia'.",
    hook: "I Caraibi d'Italia?",
    hashtags: ['costadeglidei', 'capovaticano', 'calabria', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DZRwpH6MDM-/',
    postoId: 'capovaticano-tonicello-resort',
    publishedAt: '2026-06-07',
    isPlaceholder: false,
  },
  {
    id: 'reel-pessina-agriturismo-campagnino',
    localPath: '/video/pessina-agriturismo-campagnino.mp4',
    cover: '/images/reels/pessina-agriturismo-campagnino-cover.webp',
    alt: "Campagna e tavoli all'aperto dell'Agriturismo Il Campagnino a Pessina Cremonese.",
    location: 'Pessina Cremonese · Agriturismo Il Campagnino',
    zone: 'Italia',
    type: 'Hotel con carattere',
    caption:
      'Agriturismo a Pessina Cremonese tra natura e animali: aperitivi freschi ed economici, pranzi con prodotti km0 ed esperienze didattiche — come preparare la pasta fresca e gustarla direttamente a pranzo.',
    hook: 'Un agriturismo dove fai la pasta fresca?',
    hashtags: ['agriturismo', 'lombardia', 'km0', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DY3sfZ3M8dm/',
    postoId: 'pessina-agriturismo-campagnino',
    publishedAt: '2026-05-28',
    isPlaceholder: false,
  },
  {
    id: 'reel-grone-narciso-home-chalet',
    localPath: '/video/grone-narciso-home-chalet.mp4',
    cover: '/images/reels/grone-narciso-home-chalet-cover.webp',
    alt: 'Jacuzzi riscaldata con vista sulla natura dello chalet Narciso Home a Grone.',
    location: 'Grone · Narciso Home',
    zone: 'Italia',
    type: 'Hotel con carattere',
    caption:
      'Chalet immerso nella natura a Grone (BG): jacuzzi riscaldata con vista, sauna interna e doccia emozionale. Incluso un aperitivo con prodotti del territorio e il necessario per cena e colazione. Per un weekend di coppia.',
    hook: 'Lo chalet più romantico della Lombardia?',
    hashtags: ['chalet', 'bergamo', 'weekendromantico', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DYub1jYsfA7/',
    postoId: 'grone-narciso-home-chalet',
    publishedAt: '2026-05-24',
    isPlaceholder: false,
  },
  {
    id: 'reel-garfagnana-luccarfting-kayak',
    localPath: '/video/garfagnana-luccarfting-kayak.mp4',
    cover: '/images/reels/garfagnana-luccarfting-kayak-cover.webp',
    alt: 'Kayak tra i torrenti verdi della Garfagnana con Luccarfting.',
    location: 'Toscana · Luccarfting',
    zone: 'Italia',
    type: 'Insolito',
    caption:
      'Kayak, tuffi e nuotate nei torrenti della Garfagnana: tre ore di adrenalina in compagnia, con istruttori esperti che ti seguono in sicurezza. Una delle attività proposte da Luccarfting.',
    hook: "L'attività estiva perfetta?",
    hashtags: ['garfagnana', 'kayak', 'toscana', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DYrYyrctBoC/',
    postoId: 'garfagnana-luccarfting-kayak',
    publishedAt: '2026-05-23',
    isPlaceholder: false,
  },
  {
    id: 'reel-shanghai-capyland-capibara',
    localPath: '/video/shanghai-capyland-capibara.mp4',
    cover: '/images/reels/shanghai-capyland-capibara-cover.webp',
    alt: 'Visitatori che coccolano un capibara al Capyland di Shanghai.',
    location: 'Shanghai · Capyland',
    zone: 'Asia',
    type: 'Insolito',
    caption:
      'A Shanghai, un locale dove coccolare i capibara: uno dei posti più teneri e insoliti da provare in città, per chi ama gli animali.',
    hook: 'Il locale più tenero al mondo?',
    hashtags: ['capibara', 'shanghai', 'cina', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DYmhHheMI-c/',
    postoId: 'shanghai-capyland-capibara',
    publishedAt: '2026-05-21',
    isPlaceholder: false,
  },
  {
    id: 'reel-verona-little-italy-sushi-pizza',
    localPath: '/video/verona-little-italy-sushi-pizza.mp4',
    cover: '/images/reels/verona-little-italy-sushi-pizza-cover.webp',
    alt: 'Sushi di pizza e spritz XL serviti da Little Italy a Verona.',
    location: 'Verona · Little Italy',
    zone: 'Italia',
    type: 'Food & Ristoranti',
    caption:
      "A Verona, un format unico da Little Italy: promo a 30€ con due spritz XL da mezzo litro e un 'sushi di pizza'. Per una serata diversa in città.",
    hook: 'Sushi di pizza e albero di spritz?',
    hashtags: ['verona', 'sushipizza', 'venetofood', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DYjFh4lsq4m/',
    postoId: 'verona-little-italy-sushi-pizza',
    publishedAt: '2026-05-20',
    isPlaceholder: false,
  },
  {
    id: 'reel-garfagnana-agriturismo-cornali',
    localPath: '/video/garfagnana-agriturismo-cornali.mp4',
    cover: '/images/reels/garfagnana-agriturismo-cornali-cover.webp',
    alt: "Piscina privata e verde dell'Agriturismo Cornali in Garfagnana.",
    location: 'Toscana · Agriturismo Cornali',
    zone: 'Italia',
    type: 'Hotel con carattere',
    caption:
      'In Garfagnana, agriturismo a conduzione familiare immerso nel verde: spa, piscina privata, colazioni fatte in casa e appartamenti spaziosi. Base ideale per borghi, eremi e grotte della zona.',
    hook: 'Una zona sottovalutata della Toscana?',
    hashtags: ['garfagnana', 'agriturismo', 'toscana', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/reel/DYePI7Us3sk/',
    postoId: 'garfagnana-agriturismo-cornali',
    publishedAt: '2026-05-18',
    isPlaceholder: false,
  },
  {
    id: 'reel-shanghai-disneyland',
    localPath: '/video/shanghai-disneyland.mp4',
    cover: '/images/reels/shanghai-disneyland-cover.webp',
    alt: 'Betta a braccia alzate davanti al castello di Shanghai Disneyland, sotto il cielo azzurro.',
    location: 'Shanghai · Disneyland',
    zone: 'Asia',
    type: 'Posti particolari',
    caption:
      "Non è il parco Disney con più attrazioni adrenaliniche, ma è quello che ti fa tornare bambino: principesse, personaggi e scenari da fiaba. L'attrazione in barca è stata la nostra preferita. Per chi cerca atmosfera più che velocità.",
    hook: "L'attrazione più emozionante di sempre?",
    hashtags: ['disneylandshanghai', 'shanghai', 'consigliviaggio'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/Db2nDlaM11X/',
    postoId: 'shanghai-disneyland',
    publishedAt: '2026-08-10',
    isPlaceholder: false,
  },
  {
    id: 'reel-madrid-churreria-1902',
    localPath: '/video/madrid-churreria-1902.mp4',
    cover: '/images/reels/madrid-churreria-1902-cover.webp',
    alt: 'Piatto di churros e tazza di cioccolata calda sotto l’insegna della Churrería Chocolatería 1902 a Madrid.',
    location: 'Madrid · Churrería Chocolatería 1902',
    zone: 'Europa',
    type: 'Food & Ristoranti',
    caption:
      'A Madrid i churros si mangiano ovunque, ma qui li vedi fare dal bancone. Abbiamo preso una porzione normale, una di churros giganti e una cioccolata: 8€ in due. Per una colazione o una merenda senza cerimonie.',
    hook: 'La miglior churrería di Madrid?',
    hashtags: ['churrosmadrid', 'madridfood', 'cibomadrid'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DbaXDLrMSeS/',
    postoId: 'madrid-churreria-1902',
    publishedAt: '2026-07-30',
    isPlaceholder: false,
  },
  {
    id: 'reel-san-donato-yoi-sushi',
    localPath: '/video/san-donato-yoi-sushi.mp4',
    cover: '/images/reels/san-donato-yoi-sushi-cover.webp',
    alt: 'Ruota panoramica dorata con vaschette di sushi da Yoi Sushi, con piatti di salmone e tartare sul tavolo.',
    location: 'San Donato Milanese · Yoi Sushi',
    zone: 'Italia',
    type: 'Food & Ristoranti',
    caption:
      'Sushi servito su una ruota panoramica, roll con Wagyu e creazioni al tartufo: la presentazione è la metà del piatto. All you can eat a pranzo da 17,90€, la cena 32,90€ più 3€ di coperto, bevande e dolci esclusi.',
    hook: 'Il lunapark del sushi?',
    hashtags: ['allyoucaneat', 'milanofood', 'milanoristoranti'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DbVLl7gMo7R/',
    postoId: 'san-donato-yoi-sushi',
    publishedAt: '2026-07-28',
    isPlaceholder: false,
  },
  {
    id: 'reel-milano-wagyu-oh',
    localPath: '/video/milano-wagyu-oh.mp4',
    cover: '/images/reels/milano-wagyu-oh-cover.webp',
    alt: 'Sala di Wagyu Oh a Milano con maxischermi, luci al neon rosse e lanterne cinesi.',
    location: 'Milano · Wagyu Oh',
    zone: 'Italia',
    type: 'Food & Ristoranti',
    caption:
      'Griglia al centro del tavolo e la carne la cuoci tu: tagli di Wagyu, manzo, pesce e verdure, in una sala di maxischermi e neon. All you can eat a pranzo da 24€, cena da 36€. In via Bramante 35 a Milano.',
    hook: 'BBQ coreano con Wagyu all you can eat?',
    hashtags: ['allyoucaneat', 'milanoristoranti', 'milanofood'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DbX0AI-Mqjn/',
    postoId: 'milano-wagyu-oh',
    publishedAt: '2026-07-29',
    isPlaceholder: false,
  },
  {
    id: 'reel-bled-garden-village',
    localPath: '/video/bled-garden-village.mp4',
    cover: '/images/reels/bled-garden-village-cover.webp',
    alt: 'Tenda glamping su palafitta accanto a un torrente con piccola cascata, nel bosco del Garden Village a Bled.',
    location: 'Bled · Garden Village',
    zone: 'Europa',
    type: 'Hotel con carattere',
    caption:
      'Glamping a due passi dal lago di Bled e dalle gole di Vintgar: si sceglie fra case sull’albero, tende con tinozza calda e tende sull’acqua. Ristorante interno e colazione inclusa. Per famiglie, coppie e gruppi di amici.',
    hook: 'Dormiresti in una casa sull’albero a Bled?',
    hashtags: ['bled', 'slovenia', 'glamping', 'travelliniwithus'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DJoQoqUIRh3/',
    postoId: 'bled-garden-village',
    publishedAt: '2025-05-14',
    isPlaceholder: false,
  },
  {
    id: 'reel-kuala-lumpur-ceylonz',
    localPath: '/video/kuala-lumpur-ceylonz.mp4',
    cover: '/images/reels/kuala-lumpur-ceylonz-cover.webp',
    alt: 'Piscina a sfioro notturna del Ceylonz Suites con lo skyline di Kuala Lumpur, la KL Tower illuminata di rosso e le Petronas sullo sfondo.',
    location: 'Kuala Lumpur · Ceylonz Suites',
    zone: 'Asia',
    type: 'Hotel con carattere',
    caption:
      'A Kuala Lumpur abbiamo dormito in un appartamento con piscina a sfioro vista skyline a 25€ a notte a persona. Intorno: street food da 4€, mercati notturni, e attrazioni come Batu Caves e Chinatown in gran parte gratuite.',
    hook: 'Una delle città più economiche del mondo?',
    hashtags: ['kualalumpur', 'malesia', 'viaggioeconomico'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DNdews7ooto/',
    postoId: 'kuala-lumpur-ceylonz',
    publishedAt: '2025-08-17',
    isPlaceholder: false,
  },
  {
    id: 'reel-campania-burton-juice',
    localPath: '/video/campania-burton-juice.mp4',
    cover: '/images/reels/campania-burton-juice-cover.webp',
    alt: 'Poltrona bianca fra scacchi giganti e specchi fioriti nella sala a tema Alice del The Burton Juice a Somma Vesuviana.',
    location: 'Somma Vesuviana · The Burton Juice',
    zone: 'Italia',
    type: 'Insolito',
    caption:
      "Il primo ristorante a tema Tim Burton in Italia: location iper-tematizzata tra Jack Skeleton, Beetlejuice e Alice, menù dedicato ai personaggi e spettacoli durante la serata. Da prenotare con anticipo. Per gli amanti dell'insolito.",
    hook: 'Il primo ristorante a tema Tim Burton in Italia?',
    hashtags: ['timburton', 'sommavesuviana', 'ristorantitematici'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/C6gJr_noB_i/',
    postoId: 'campania-burton-juice',
    publishedAt: '2024-05-03',
    isPlaceholder: false,
  },
  {
    id: 'reel-roma-pasta-eat',
    localPath: '/video/roma-pasta-eat.mp4',
    cover: '/images/reels/roma-pasta-eat-cover.webp',
    alt: 'Vaschetta di pasta fresca PastaEat tenuta in mano davanti alla fontana della Barcaccia e alla scalinata di Trinità dei Monti a Roma.',
    location: 'Roma · PastaEat',
    zone: 'Italia',
    type: 'Food & Ristoranti',
    caption:
      'Poke di pasta fresca a due passi da Piazza di Spagna: scegli formato e sugo al bancone e te la preparano al momento. Amatriciana, gricia e cacio e pepe da 8€, 9,50€ le versioni al tartufo. Da mangiare in piedi guardando la città.',
    hook: 'Pasta fresca in Piazza di Spagna?',
    hashtags: ['roma', 'romafood', 'streetfood'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DU5eO2SDKKA/',
    postoId: 'roma-pasta-eat',
    publishedAt: '2026-02-18',
    isPlaceholder: false,
  },
  {
    id: 'reel-barcellona-boba-gelati',
    localPath: '/video/barcellona-boba-gelati.mp4',
    cover: '/images/reels/barcellona-boba-gelati-cover.webp',
    alt: 'Due coni gelato a forma di rana e di leone del gelato Boba, tenuti in mano su una via di Barcellona.',
    location: 'Barcellona · Boba',
    zone: 'Europa',
    type: 'Food & Ristoranti',
    caption:
      'Coni gelato a forma di animale — rana, leone — a 3,50€, più le wheelcake fatte al momento con vari ripieni. Il tipo di posto in cui si fa la fila per la foto e poi si resta per il gelato.',
    hook: 'Gelati che dispiace mangiare?',
    hashtags: ['barcellona', 'spagna', 'gelato'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DXq36b4DHwI/',
    postoId: 'barcellona-boba-gelati',
    publishedAt: '2026-04-28',
    isPlaceholder: false,
  },
  {
    id: 'reel-milano-lievita-sottocorno',
    localPath: '/video/milano-lievita-sottocorno.mp4',
    cover: '/images/reels/milano-lievita-sottocorno-cover.webp',
    alt: 'Due pizze napoletane appena portate al tavolo della pizzeria Lievità Sottocorno a Milano.',
    location: 'Milano · Lievità Sottocorno',
    zone: 'Italia',
    type: 'Food & Ristoranti',
    caption:
      'Pizzeria pluripremiata in via Sottocorno 17, pizze gourmet dalle combinazioni tradizionali a quelle più insolite. Ci siamo andati con una prenotazione TheFork, che su alcuni ristoranti sconta fino al 50%.',
    hook: 'La pizza migliore di Milano?',
    hashtags: ['milanofood', 'pizzamilano', 'pizzagourmet'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DVQabhFDKw3/',
    postoId: 'milano-lievita-sottocorno',
    publishedAt: '2026-02-27',
    isPlaceholder: false,
  },
  {
    id: 'reel-bruhl-phantasialand',
    localPath: '/video/bruhl-phantasialand.mp4',
    cover: '/images/reels/bruhl-phantasialand-cover.webp',
    alt: 'Veicolo steampunk arrugginito davanti a un arco di mattoni, alla scenografia di ingresso di un’attrazione di Phantasialand a Brühl.',
    location: 'Brühl · Phantasialand',
    zone: 'Europa',
    type: 'Posti particolari',
    caption:
      "Parco tedesco a sud di Colonia, tematizzato fino all'ultimo bullone. Nell'area Mexico c'è una delle attrazioni più adrenaliniche che abbiamo provato: due minuti e basta, ma si ricordano.",
    hook: 'Avresti il coraggio di salirci?',
    hashtags: ['phantasialand', 'parcodivertimenti', 'germania'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DVGF2bEDBVj/',
    postoId: 'bruhl-phantasialand',
    publishedAt: '2026-02-23',
    isPlaceholder: false,
  },
  {
    id: 'reel-frosinone-ora-ristorante',
    localPath: '/video/frosinone-ora-ristorante.mp4',
    cover: '/images/reels/frosinone-ora-ristorante-cover.webp',
    alt: 'Tavolo apparecchiato con tovaglia bianca e un grande orsacchiotto seduto a fianco, nella sala di Ora Ristorante a Frosinone.',
    location: 'Frosinone · Ora Ristorante',
    zone: 'Italia',
    type: 'Food & Ristoranti',
    caption:
      'Tre menù degustazione e una sala piccola e curata. Abbiamo scelto il "Santa Pazienza", sette portate: piatti particolari, servizio attento dall’inizio alla fine. Da prenotare, non è un posto da passaggio.',
    hook: 'Una cena che va oltre le candele?',
    hashtags: ['frosinone', 'ristorantilazio', 'menudegustazione'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DUp5VIDjDuZ/',
    postoId: 'frosinone-ora-ristorante',
    publishedAt: '2026-02-12',
    isPlaceholder: false,
  },
  {
    id: 'reel-milano-jazz-cafe',
    localPath: '/video/milano-jazz-cafe.mp4',
    cover: '/images/reels/milano-jazz-cafe-cover.webp',
    alt: 'Sala del Jazz Café di Milano con pavimento a scacchi bianco e nero, tende rosse di velluto e tavoli apparecchiati.',
    location: 'Milano · Jazz Café',
    zone: 'Italia',
    type: 'Insolito',
    caption:
      'Cena con spettacolo: si mangia, poi il locale si accende e arrivano musica live e ballerine. Sala elegante, pavimento a scacchi e tende rosse. Serata lunga: non è la cena di chi vuole parlare.',
    hook: 'Una serata al "Moulin Rouge"?',
    hashtags: ['milano', 'cenaspettacolo', 'localimilano'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DUkt_gEjGuW/',
    postoId: 'milano-jazz-cafe',
    publishedAt: '2026-02-10',
    isPlaceholder: false,
  },
  {
    id: 'reel-mantova-ramen-ramen',
    localPath: '/video/mantova-ramen-ramen.mp4',
    cover: '/images/reels/mantova-ramen-ramen-cover.webp',
    alt: 'Ingresso di Ramen Ramen a Mantova con lanterne giapponesi arancioni accese e una grande stampa ukiyo-e alle pareti.',
    location: 'Mantova · Ramen Ramen',
    zone: 'Italia',
    type: 'Food & Ristoranti',
    caption:
      'Ramen con la raclette colata sopra, noodle freschi e brodi da scegliere, in una sala scura con lanterne e roccia a vista. Buoni anche i takoyaki e i bao.',
    hook: 'Formaggio fuso dentro il ramen?',
    hashtags: ['mantovafood', 'ramen', 'lombardiafood'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DTsrXx1DMf1/',
    postoId: 'mantova-ramen-ramen',
    publishedAt: '2026-01-19',
    isPlaceholder: false,
  },
  {
    id: 'reel-volterra-antica-velathri',
    localPath: '/video/volterra-antica-velathri.mp4',
    cover: '/images/reels/volterra-antica-velathri-cover.webp',
    alt: 'Cocktail nero con guarnizione dorata e una fiamma azzurra accesa sul tagliere, al bancone dell’Antica Velathri Cafe a Volterra.',
    location: 'Volterra · Antica Velathri Cafe',
    zone: 'Italia',
    type: 'Insolito',
    caption:
      "Menù ispirato all'alchimia dentro uno dei borghi più belli d'Italia: drink serviti con fiamme e alambicchi, prodotti toscani. È da anni il nostro posto del cuore a Volterra, e cambia ogni volta che torniamo.",
    hook: 'Un aperitivo che prende fuoco?',
    hashtags: ['volterra', 'toscana', 'cocktailbar'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DTPz9hJDN9G/',
    postoId: 'volterra-antica-velathri',
    publishedAt: '2026-01-08',
    isPlaceholder: false,
  },
  {
    id: 'reel-praga-cinnamood',
    localPath: '/video/praga-cinnamood.mp4',
    cover: '/images/reels/praga-cinnamood-cover.webp',
    alt: 'Vetrina della pasticceria Cinnamood a Praga con l’insegna sopra la porta e la lavagna dei cinnamon roll sul marciapiede.',
    location: 'Praga · Cinnamood',
    zone: 'Europa',
    type: 'Food & Ristoranti',
    caption:
      'Pasticceria diventata virale sui social, e per una volta il posto regge la fama: cinnamon roll enormi, farciture diverse ogni giorno, caffetteria di specialità. Coda quasi sempre.',
    hook: 'I cinnamon roll più virali del web?',
    hashtags: ['praga', 'pragafood', 'cinnamonroll'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DS5WO47jNI5/',
    postoId: 'praga-cinnamood',
    publishedAt: '2025-12-30',
    isPlaceholder: false,
  },
  {
    id: 'reel-verona-bbq-magi',
    localPath: '/video/verona-bbq-magi.mp4',
    cover: '/images/reels/verona-bbq-magi-cover.webp',
    alt: 'Tavolo con griglia integrata e vassoi di carne cruda avvolti dal fumo, nella sala di Magi BBQ a Verona.',
    location: 'Verona · Magi BBQ',
    zone: 'Italia',
    type: 'Food & Ristoranti',
    caption:
      'Barbecue coreano illimitato a 19,90€: carni da grigliare al tavolo e contorni senza limite. Per chi vuole mangiare molto e bene spendendo poco.',
    hook: 'Un BBQ coreano illimitato a Verona?',
    hashtags: ['verona', 'bbqcoreano', 'allyoucaneat'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DSM14K0jV5r/',
    postoId: 'verona-bbq-magi',
    publishedAt: '2025-12-13',
    isPlaceholder: false,
  },
  {
    id: 'reel-firenze-villa-tolomei',
    localPath: '/video/firenze-villa-tolomei.mp4',
    cover: '/images/reels/firenze-villa-tolomei-cover.webp',
    alt: 'Viale di cipressi che scende verso la collina con Firenze sullo sfondo, davanti a Villa Tolomei.',
    location: 'Firenze · Villa Tolomei',
    zone: 'Italia',
    type: 'Hotel con carattere',
    caption:
      'Villa del 1200 sulle colline sopra Firenze: due ore di spa privata con sauna e bagno turco, massaggio di coppia, piscina panoramica esterna con la città sullo sfondo. Un viale di cipressi porta all’ingresso.',
    hook: 'Un weekend con Firenze davanti?',
    hashtags: ['firenze', 'toscana', 'weekendromantico'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DSJxfijDO-V/',
    postoId: 'firenze-villa-tolomei',
    publishedAt: '2025-12-12',
    isPlaceholder: false,
  },
  {
    id: 'reel-prato-taverna-orco',
    localPath: '/video/prato-taverna-orco.mp4',
    cover: '/images/reels/prato-taverna-orco-cover.webp',
    alt: 'Statua di un orco a grandezza naturale dietro il bancone della Taverna dell’Orco a Prato, con un piatto di grigliata in primo piano.',
    location: "Prato · La Taverna dell'Orco",
    zone: 'Italia',
    type: 'Insolito',
    caption:
      'Locale fantasy curato in ogni angolo, con un orco a grandezza naturale dietro al bancone e un menù scritto come un manuale di gioco. Porzioni grandi, da condividere, e bevande colorate a tema.',
    hook: 'Un pub dove comanda un orco?',
    hashtags: ['prato', 'toscana', 'pubtematici'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DRufmWEjPjf/',
    postoId: 'prato-taverna-orco',
    publishedAt: '2025-12-01',
    isPlaceholder: false,
  },
  {
    id: 'reel-lubiana-wonderland',
    localPath: '/video/lubiana-wonderland.mp4',
    cover: '/images/reels/lubiana-wonderland-cover.webp',
    alt: 'Sala di Wonderland a Lubiana con pareti interamente coperte di fiori, un albero scolpito bianco e un’insegna al neon.',
    location: 'Lubiana · Wonderland',
    zone: 'Europa',
    type: 'Insolito',
    caption:
      'Sale coperte di fiori, un albero scolpito che attraversa il soffitto e luci basse: a Lubiana è il posto in cui si va per il brunch e si resta per i dolci scenografici e i drink.',
    hook: 'Il paese delle meraviglie esiste?',
    hashtags: ['lubiana', 'slovenia', 'brunch'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DRBtFeWDOdJ/',
    postoId: 'lubiana-wonderland',
    publishedAt: '2025-11-14',
    isPlaceholder: false,
  },
  {
    id: 'reel-torino-choco-story',
    localPath: '/video/torino-choco-story.mp4',
    cover: '/images/reels/torino-choco-story-cover.webp',
    alt: 'Sculture di cioccolato a forma di Topolino e di altri personaggi dentro una teca del museo Choco Story a Torino.',
    location: 'Torino · Choco Story',
    zone: 'Italia',
    type: 'Posti particolari',
    caption:
      'Museo del cioccolato e del gianduja: percorso con audioguida inclusa, postazioni interattive e degustazione finale. 12€ per gli adulti, 10€ fino ai 26 anni. Si visita in autonomia, senza orari di gruppo.',
    hook: 'La fabbrica del cioccolato esiste?',
    hashtags: ['torino', 'piemonte', 'museocioccolato'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DQ8hTM_DK_Y/',
    postoId: 'torino-choco-story',
    publishedAt: '2025-11-12',
    isPlaceholder: false,
  },
  {
    id: 'reel-torino-panda-q',
    localPath: '/video/torino-panda-q.mp4',
    cover: '/images/reels/torino-panda-q-cover.webp',
    alt: 'Sala del ristorante Panda Q a Torino con peluche di panda sui mobili e un ventaglio decorato sul tavolo.',
    location: 'Torino · Panda Q',
    zone: 'Italia',
    type: 'Food & Ristoranti',
    caption:
      "Peluche di panda ovunque e decorazioni a tema, ma la cucina è cinese vera: i ravioli si preparano al momento. L'aspetto kawaii inganna — si mangia sul serio.",
    hook: 'Un ristorante invaso dai panda?',
    hashtags: ['torino', 'cucinacinese', 'ristorantitematici'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DQW4hVejK_A/',
    postoId: 'torino-panda-q',
    publishedAt: '2025-10-28',
    isPlaceholder: false,
  },
  {
    id: 'reel-emilia-granduca-di-campigna',
    localPath: '/video/emilia-granduca-di-campigna.mp4',
    cover: '/images/reels/emilia-granduca-di-campigna-cover.webp',
    alt: 'Piscina interna illuminata di blu nella spa ricavata in una grotta di pietra del Granduca wellness hotel a Campigna.',
    location: 'Campigna · Granduca Wellness Hotel',
    zone: 'Italia',
    type: 'Relax, terme e spa',
    caption:
      'Un wellness hotel immerso nelle foreste casentinesi (patrimonio UNESCO): appartamenti spaziosi, alcuni con jacuzzi in camera, spa con aperitivo nella grotta e cena di prodotti locali servita in camera. Vale la pena per chi cerca un weekend romantico vero, lontano dal caos.',
    hook: 'Il posto perfetto per un weekend romantico?',
    hashtags: ['foresteCasentinesi', 'weekendromantico', 'spa'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DTkfltMDGVo/',
    postoId: 'emilia-granduca-di-campigna',
    publishedAt: '2026-01-16',
    isPlaceholder: false,
  },
  {
    id: 'reel-rust-europa-park',
    localPath: '/video/rust-europa-park.mp4',
    cover: '/images/reels/rust-europa-park-cover.webp',
    alt: 'Selfie di gruppo nella piscina del bar acquatico di Rulantica, dentro Europa-Park a Rust, con un bicchiere di birra in primo piano.',
    location: 'Rust · Europa-Park',
    zone: 'Europa',
    type: 'Posti particolari',
    caption:
      'Oltre cento attrazioni e code che restano sui 40-50 minuti, con pass gratuiti per saltare la fila sulle principali. Le nostre preferite: Voltron e Wodan, il colosso in legno. Dentro c’è anche Rulantica, il parco acquatico coperto.',
    hook: 'Il parco più bello d’Europa?',
    hashtags: ['europapark', 'rust', 'parcodivertimenti'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DW-3Lu4jCUg/',
    postoId: 'rust-europa-park',
    publishedAt: '2026-04-11',
    isPlaceholder: false,
  },
  {
    id: 'reel-penang-bao-teck',
    localPath: '/video/penang-bao-teck.mp4',
    cover: '/images/reels/penang-bao-teck-cover.webp',
    alt: 'Sala della Bao Teck Tea House a Penang con tavoli rotondi, lampadari dorati e piante pendenti da un tronco.',
    location: 'Penang · Bao Teck Tea House',
    zone: 'Asia',
    type: 'Food & Ristoranti',
    caption:
      'Sala coloniale con lampadari dorati e piante pendenti, nel cuore di George Town. Si sceglie fra tanti tipi di tè, dolcetti tipici e piccoli piatti in stile dim sum. Pausa tranquilla fra un giro e l’altro.',
    hook: 'Una vera tea house asiatica?',
    hashtags: ['penang', 'malesia', 'dimsum'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DP284FmjHlB/',
    postoId: 'penang-bao-teck',
    publishedAt: '2025-10-16',
    isPlaceholder: false,
  },
  {
    id: 'reel-padova-la-pot',
    localPath: '/video/padova-la-pot.mp4',
    cover: '/images/reels/padova-la-pot-cover.webp',
    alt: 'Quattro vassoi di carne cruda marinata tenuti in mano da LaPot a Padova, davanti alla griglia incassata nel tavolo.',
    location: 'Padova · LaPot',
    zone: 'Italia',
    type: 'Food & Ristoranti',
    caption:
      'All you can eat con la griglia al centro del tavolo: tanti tagli di carne, spiedini cinesi, pesce, verdure e wagyu. Le salse te le componi tu. Serata lunga e conviviale, non una cena veloce.',
    hook: 'Hai mai provato il BBQ coreano?',
    hashtags: ['padova', 'bbqcoreano', 'allyoucaneat'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DP0y9-6DJ0j/',
    postoId: 'padova-la-pot',
    publishedAt: '2025-10-15',
    isPlaceholder: false,
  },
  {
    id: 'reel-casola-spino-fiorito',
    localPath: '/video/casola-spino-fiorito.mp4',
    cover: '/images/reels/casola-spino-fiorito-cover.webp',
    alt: 'Sauna con vetrata sul bosco e sulle montagne della Lunigiana, nella mirror house Spino Fiorito a Casola.',
    location: 'Casola in Lunigiana · Spino Fiorito',
    zone: 'Italia',
    type: 'Hotel con carattere',
    caption:
      'Alloggio rivestito di specchi che riflettono il bosco intorno e cambiano colore con la luce del giorno, in Lunigiana. Dentro c’è la sauna con vetrata sulle montagne. Si arriva in auto, poi si sta.',
    hook: 'Dormiresti in una mirror house?',
    hashtags: ['lunigiana', 'mirrorhouse', 'toscana'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DPmpX6cDGVZ/',
    postoId: 'casola-spino-fiorito',
    publishedAt: '2025-10-09',
    isPlaceholder: false,
  },
  {
    id: 'reel-treviso-nonno-andrea',
    localPath: '/video/treviso-nonno-andrea.mp4',
    cover: '/images/reels/treviso-nonno-andrea-cover.webp',
    alt: 'Campo di zucche con una piramide di zucche colorate e uno spaventapasseri gigante al villaggio di Nonno Andrea a Villorba.',
    location: 'Villorba · Nonno Andrea',
    zone: 'Italia',
    type: 'Posti particolari',
    caption:
      'Uno dei villaggi delle zucche più grandi del Nord Italia: sculture di zucca, casette in stile americano, aree tematiche e spettacoli. Ingresso 10€ infrasettimanale, 12€ nel weekend. Da provare il risotto e il cappuccino alla zucca.',
    hook: 'Il villaggio delle zucche?',
    hashtags: ['zucche', 'halloween', 'veneto'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DPfs_FgDDwM/',
    postoId: 'treviso-nonno-andrea',
    publishedAt: '2025-10-07',
    isPlaceholder: false,
  },
  {
    id: 'reel-bracciano-enjoy-house',
    localPath: '/video/bracciano-enjoy-house.mp4',
    cover: '/images/reels/bracciano-enjoy-house-cover.webp',
    alt: 'Jacuzzi piena di schiuma con luci azzurre e un tagliere di salumi e fritti sul bordo, in una suite di Enjoy House a Bracciano.',
    location: 'Bracciano · Enjoy House',
    zone: 'Italia',
    type: 'Hotel con carattere',
    caption:
      'Suite con jacuzzi privata in camera e aperitivo servito a bordo vasca, dentro un borgo medievale affacciato sul lago di Bracciano. Il borgo si gira a piedi, con calma.',
    hook: 'Aperitivo dentro la jacuzzi?',
    hashtags: ['bracciano', 'lazio', 'weekendromantico'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DPUlZIZDJ6D/',
    postoId: 'bracciano-enjoy-house',
    publishedAt: '2025-10-02',
    isPlaceholder: false,
  },
  {
    id: 'reel-novellara-mamma-mia',
    localPath: '/video/novellara-mamma-mia.mp4',
    cover: '/images/reels/novellara-mamma-mia-cover.webp',
    alt: 'Due coni di pizza fritta in cestelli di metallo, tenuti in mano davanti a una parete di verde con insegne al neon da Mamma Mia a Novellara.',
    location: 'Novellara · Mamma Mia',
    zone: 'Italia',
    type: 'Food & Ristoranti',
    caption:
      'Pizza fritta servita a cono, con ripieni che vanno dal guanciale e gamberi al pulled pork. Si mangia in piedi, con le mani, davanti a una parete di verde e neon.',
    hook: 'Coni di pizza fritta?',
    hashtags: ['novellara', 'emiliaromagna', 'pizzafritta'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DPQkvGxDNL8/',
    postoId: 'novellara-mamma-mia',
    publishedAt: '2025-10-01',
    isPlaceholder: false,
  },
  {
    id: 'reel-pomigliano-the-sign',
    localPath: '/video/pomigliano-the-sign.mp4',
    cover: '/images/reels/pomigliano-the-sign-cover.webp',
    alt: 'Bancone in legno intagliato con motivi celtici e lampadari a corona nella sala del pub The Sign a Pomigliano d’Arco.',
    location: "Pomigliano d'Arco · The Sign",
    zone: 'Italia',
    type: 'Insolito',
    caption:
      'Pub fantasy dove ogni sala porta in un mondo diverso, fra intagli celtici, roccia finta e lampadari a corona. Organizzano serate a tema e sessioni di giochi di ruolo.',
    hook: 'La Terra di Mezzo esiste?',
    hashtags: ['napoli', 'pubfantasy', 'localiparticolari'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DPA2fwZDMzz/',
    postoId: 'pomigliano-the-sign',
    publishedAt: '2025-09-25',
    isPlaceholder: false,
  },
  {
    id: 'reel-the-sense-resort',
    localPath: '/video/the-sense-resort.mp4',
    cover: '/images/reels/the-sense-resort-cover.webp',
    alt: 'Tavolo apparecchiato in riva al mare al tramonto, con una coppia affacciata alla ringhiera, al The Sense Resort di Follonica.',
    location: 'Follonica · The Sense Resort',
    zone: 'Italia',
    type: 'Hotel con carattere',
    caption:
      'Resort sulla spiaggia di Follonica: cabana privata per l’aperitivo al tramonto, camere con vista mare e il ristorante Eaté proprio in riva. La sera si cena col rumore dell’acqua.',
    hook: 'Il tramonto più bello della Maremma?',
    hashtags: ['maremma', 'toscana', 'fugaromantica'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DO0b3-DDPSh/',
    postoId: 'the-sense-resort',
    publishedAt: '2025-09-20',
    isPlaceholder: false,
  },
  {
    id: 'reel-poppi-fattorie-di-celli',
    localPath: '/video/poppi-fattorie-di-celli.mp4',
    cover: '/images/reels/poppi-fattorie-di-celli-cover.webp',
    alt: 'Coppia sdraiata su cuscini sopra una rete sospesa fra gli alberi del bosco, alle Fattorie di Celli a Poppi.',
    location: 'Poppi · Fattorie di Celli',
    zone: 'Italia',
    type: 'Hotel con carattere',
    caption:
      'Reti sospese fra i tronchi, con cuscini, dentro il bosco del Casentino: ci si sdraia sopra e sotto c’è il vuoto. Alloggi immersi nella natura, a due passi da Poppi.',
    hook: 'Dormiresti su una rete sospesa fra gli alberi?',
    hashtags: ['casentino', 'toscana', 'treehouse'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DOoHsTmjCQw/',
    postoId: 'poppi-fattorie-di-celli',
    publishedAt: '2025-09-15',
    isPlaceholder: false,
  },
  {
    id: 'reel-penang-iconic-marjorie',
    localPath: '/video/penang-iconic-marjorie.mp4',
    cover: '/images/reels/penang-iconic-marjorie-cover.webp',
    alt: 'Poltrona sospesa in vimini davanti alla vetrata sulla terrazza con ombrelloni e palme dell’Iconic Marjorie Hotel a Penang.',
    location: 'Penang · Iconic Marjorie Hotel',
    zone: 'Asia',
    type: 'Hotel con carattere',
    caption:
      'Hotel nuovo a Penang, con colazione abbondante e piscina panoramica sulla città. Base comoda per girare George Town senza spendere quanto costerebbe altrove.',
    hook: 'Com’è un 5 stelle in Malesia?',
    hashtags: ['penang', 'malesia', 'hotel'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DOEM45XDMaO/',
    postoId: 'penang-iconic-marjorie',
    publishedAt: '2025-09-01',
    isPlaceholder: false,
  },
  {
    id: 'reel-kuala-lumpur-raito-izakaya',
    localPath: '/video/kuala-lumpur-raito-izakaya.mp4',
    cover: '/images/reels/kuala-lumpur-raito-izakaya-cover.webp',
    alt: 'Scala rossa illuminata fra pareti di bottiglie retroilluminate nel locale Raito Izakaya a Kuala Lumpur.',
    location: 'Kuala Lumpur · Raito Izakaya',
    zone: 'Asia',
    type: 'Food & Ristoranti',
    caption:
      'Izakaya a Kuala Lumpur costruito attorno a una scala fra pareti di bottiglie rosse illuminate. Cocktail dai gusti insoliti e carta lunga: si va per l’atmosfera quanto per il cibo.',
    hook: 'Cenare in un izakaya giapponese?',
    hashtags: ['kualalumpur', 'izakaya', 'malesia'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DNN0nl9Izu9/',
    postoId: 'kuala-lumpur-raito-izakaya',
    publishedAt: '2025-08-11',
    isPlaceholder: false,
  },
  {
    id: 'reel-massa-lubrense-relais-freedom',
    localPath: '/video/massa-lubrense-relais-freedom.mp4',
    cover: '/images/reels/massa-lubrense-relais-freedom-cover.webp',
    alt: 'Due persone sedute su un lettino su una terrazza affacciata sul mare della costiera sorrentina, con Capri all’orizzonte, al Relais Freedom Club.',
    location: 'Massa Lubrense · Relais Freedom Club',
    zone: 'Italia',
    type: 'Relax, terme e spa',
    caption:
      'Terrazza sulla costiera sorrentina con Capri davanti: piscina, jacuzzi vista mare, lettini e bar a bordo vasca. Si sta lì tutto il giorno, è quello il punto.',
    hook: 'La piscina più panoramica della costiera?',
    hashtags: ['costierasorrentina', 'campania', 'piscinapanoramica'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DNDONt4IXuR/',
    postoId: 'massa-lubrense-relais-freedom',
    publishedAt: '2025-08-07',
    isPlaceholder: false,
  },
  {
    id: 'reel-seriate-impero-sushi',
    localPath: '/video/seriate-impero-sushi.mp4',
    cover: '/images/reels/seriate-impero-sushi-cover.webp',
    alt: 'Sala di Impero Sushi a Seriate con pavimento di marmo scuro, colonne dorate, felci sospese e fumo basso sulla scalinata.',
    location: 'Seriate · Impero Sushi',
    zone: 'Italia',
    type: 'Food & Ristoranti',
    caption:
      'Sala di marmo scuro, ottone e felci sospese alle porte di Bergamo, con piatti creativi che mescolano tecnica giapponese e ingredienti italiani. Più ristorante che all you can eat.',
    hook: 'Sushi con proposte italiane?',
    hashtags: ['bergamo', 'sushi', 'lombardia'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DM0OWpIoaKN/',
    postoId: 'seriate-impero-sushi',
    publishedAt: '2025-08-01',
    isPlaceholder: false,
  },
  {
    id: 'reel-negrar-giardino-pojega',
    localPath: '/video/negrar-giardino-pojega.mp4',
    cover: '/images/reels/negrar-giardino-pojega-cover.webp',
    alt: 'Coppia che si abbraccia davanti al ninfeo in pietra e alle siepi geometriche del Giardino di Pojega a Negrar di Valpolicella.',
    location: 'Negrar di Valpolicella · Giardino di Pojega',
    zone: 'Italia',
    type: 'Posti particolari',
    caption:
      'Giardino all’italiana disegnato a fine Settecento da Luigi Trezza, con siepi geometriche, ninfeo e teatro di verzura. Poco conosciuto anche da chi vive in zona.',
    hook: 'Un giardino segreto in Valpolicella?',
    hashtags: ['valpolicella', 'veneto', 'giardinistorici'],
    instagramUrl: 'https://www.instagram.com/travelliniwithus/reel/DMfqJ_iIgC7/',
    postoId: 'negrar-giardino-pojega',
    publishedAt: '2025-07-24',
    isPlaceholder: false,
  },
];

/**
 * Reel reali pubblicati. I primi 5 (2026-06-18) hanno i frame estratti dai MP4;
 * gli altri (2026-07-24) sono cover ufficiali IG acquisite via yt-dlp dai reel
 * del profilo. Tutti visibili. Per nasconderne uno: rimuovere il suo id da qui.
 */
const VISIBLE_REEL_IDS = new Set<string>([
  'reel-lombardia-agriturismo-graffignana',
  'reel-verona-vigna-benini',
  'reel-chioggia-sand-beach',
  'reel-jesolo-caribe-bay',
  'reel-madrid-storyland-disney',
  'reel-lombardia-al-mago-medievale',
  'reel-capovaticano-tonicello-resort',
  'reel-pessina-agriturismo-campagnino',
  'reel-grone-narciso-home-chalet',
  'reel-garfagnana-luccarfting-kayak',
  'reel-shanghai-capyland-capibara',
  'reel-verona-little-italy-sushi-pizza',
  'reel-garfagnana-agriturismo-cornali',
  'reel-novara-emotional-grand-motel',
  'reel-rust-rulantica-waterpark',
  'reel-sirmione-hotel-lugana-parco',
  'reel-iseo-flyboard-pisogne',
  'reel-como-haru-sushi',
  'reel-lazise-movieland-caneva',
  'reel-montepulciano-altro-cantuccio',
  'reel-ravenna-better-sushi',
  'reel-sarteano-chiostro-cennini',
  'reel-londra-warner-bros-studio-harry-potter',
  'reel-madrid-la-santoria',
  'reel-asciano-casa-lavanda-podere-fossaccio',
  'reel-verona-casabarca',
  'reel-valeggio-parco-cavour',
  'reel-cancun-riu-messico',
  'reel-toscana-suite-spa-civico-4',
  // Tranche 2026-08-11 (yt-dlp anonimo dai reel pubblici del profilo).
  'reel-shanghai-disneyland',
  'reel-madrid-churreria-1902',
  'reel-san-donato-yoi-sushi',
  'reel-milano-wagyu-oh',
  'reel-bled-garden-village',
  'reel-kuala-lumpur-ceylonz',
  'reel-campania-burton-juice',
  'reel-rust-europa-park',
  'reel-penang-bao-teck',
  'reel-padova-la-pot',
  'reel-casola-spino-fiorito',
  'reel-treviso-nonno-andrea',
  'reel-bracciano-enjoy-house',
  'reel-novellara-mamma-mia',
  'reel-pomigliano-the-sign',
  'reel-the-sense-resort',
  'reel-poppi-fattorie-di-celli',
  'reel-penang-iconic-marjorie',
  'reel-kuala-lumpur-raito-izakaya',
  'reel-massa-lubrense-relais-freedom',
  'reel-seriate-impero-sushi',
  'reel-negrar-giardino-pojega',
  'reel-roma-pasta-eat',
  'reel-barcellona-boba-gelati',
  'reel-milano-lievita-sottocorno',
  'reel-bruhl-phantasialand',
  'reel-frosinone-ora-ristorante',
  'reel-milano-jazz-cafe',
  'reel-mantova-ramen-ramen',
  'reel-volterra-antica-velathri',
  'reel-praga-cinnamood',
  'reel-verona-bbq-magi',
  'reel-firenze-villa-tolomei',
  'reel-prato-taverna-orco',
  'reel-lubiana-wonderland',
  'reel-torino-choco-story',
  'reel-torino-panda-q',
  'reel-emilia-granduca-di-campigna',
]);

export const REELS: ReelEntry[] = RAW_REELS.filter((reel) => VISIBLE_REEL_IDS.has(reel.id)).map(
  (reel) => ({ ...reel, localPath: resolveVideoUrl(reel.localPath) })
);

/**
 * Helper: ritorna i reel pubblicabili (non placeholder), ordinati per views
 * decrescenti. Usato da HeroSection per scegliere il FEATURED_REEL e da
 * InstagramGrid per popolare la griglia.
 */
export function getPublishedReels(): ReelEntry[] {
  return REELS.filter((reel) => !reel.isPlaceholder).sort(
    (a, b) => (b.views ?? 0) - (a.views ?? 0)
  );
}

/**
 * Helper: ritorna il reel più rilevante per una zona (se esiste).
 * Usato da /esplora come anchor visivo quando l'utente filtra `?zone=X`.
 */
export function getReelForZone(zone: Zone): ReelEntry | null {
  return getPublishedReels().find((reel) => reel.zone === zone) ?? null;
}

/**
 * Helper: ritorna il reel più rilevante per un tipo (se esiste).
 * Usato da /esplora come anchor visivo quando l'utente filtra `?type=X`.
 */
export function getReelForType(type: ContentType): ReelEntry | null {
  return getPublishedReels().find((reel) => reel.type === type) ?? null;
}

/**
 * Helper: il reel girato in un posto preciso (se esiste).
 * Usato dalla scheda `/posto/<id>`, dove finora il video del posto esisteva ma
 * si poteva vedere solo altrove: da qui si usciva su Instagram.
 */
export function getReelForPosto(postoId: string): ReelEntry | null {
  return getPublishedReels().find((reel) => reel.postoId === postoId) ?? null;
}
