import React, { useState } from 'react';

interface OptimizedImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
  src?: string;
  alt?: string;
  sizes?: string;
  width?: number;
  height?: number;
  /** Disable the warm color filter (enabled by default) */
  warm?: boolean;
  /** Prioritize loading for above-the-fold imagery */
  priority?: boolean;
  /** Use local resized variants generated by scripts/optimize-images.mjs */
  responsiveWidths?: number[];
  /** Include il file base (senza suffisso) nel srcSet locale con questa
   *  larghezza — es. 1080 quando le varianti sono -320/-480/-768 e la
   *  sorgente è già larga 1080px. */
  baseWidth?: number;
}

interface ResponsiveSources {
  srcSet: string;
  defaultSrc: string;
  avifSrcSet?: string;
}

/**
 * Generates responsive srcSet for supported CDN image sources.
 * Supports: Unsplash, Firebase Storage (via image resize extension).
 * Falls through for other sources.
 */
function getResponsiveSrcSet(src: string): ResponsiveSources | null {
  const widths = [400, 800, 1200, 1920, 2560];

  if (src.includes('unsplash.com')) {
    const baseUrl = src.replace(/[?&]w=\d+/, '').replace(/[?&]$/, '');
    const separator = baseUrl.includes('?') ? '&' : '?';

    const srcSet = widths
      .map((w) => `${baseUrl}${separator}w=${w}&auto=format&fit=crop&q=80 ${w}w`)
      .join(', ');

    const avifSrcSet = widths
      .map((w) => `${baseUrl}${separator}w=${w}&fm=avif&fit=crop&q=70 ${w}w`)
      .join(', ');

    const defaultSrc = `${baseUrl}${separator}w=1200&auto=format&fit=crop&q=80`;
    return { srcSet, defaultSrc, avifSrcSet };
  }

  if (src.includes('firebasestorage.googleapis.com')) {
    const srcSet = widths
      .map((w) => {
        const resizedUrl = src.replace(/(\.[a-z]+)(\?)/i, `_${w}x${w}$1$2`);
        return `${resizedUrl} ${w}w`;
      })
      .join(', ');

    return { srcSet, defaultSrc: src };
  }

  return null;
}

/** Inline SVG data URI for a minimal brand-coloured placeholder. */
const FALLBACK_PLACEHOLDER =
  "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='300' fill='none'%3E%3Crect width='400' height='300' rx='12' fill='%23f5f0eb'/%3E%3Cpath d='M175 170l25-40 25 40z M210 170l20-28 20 28z' fill='%23e0d5c8'/%3E%3Ccircle cx='175' cy='125' r='12' fill='%23e0d5c8'/%3E%3C/svg%3E";

export default function OptimizedImage({
  src,
  alt = '',
  className,
  sizes,
  width,
  height,
  warm = false,
  priority = false,
  responsiveWidths,
  baseWidth,
  onLoad,
  onError,
  ...props
}: OptimizedImageProps) {
  const [loaded, setLoaded] = useState(false);
  const [errored, setErrored] = useState(false);

  if (!src) return null;

  // If the image has errored, render the fallback placeholder gracefully.
  if (errored) {
    return (
      <img
        alt={alt}
        src={FALLBACK_PLACEHOLDER}
        className={`${className || ''} opacity-60`.trim()}
        width={width}
        height={height}
        aria-label={alt || 'Immagine non disponibile'}
      />
    );
  }

  const handleLoad: React.ReactEventHandler<HTMLImageElement> = (event) => {
    setLoaded(true);
    onLoad?.(event);
  };

  const handleError: React.ReactEventHandler<HTMLImageElement> = (event) => {
    setErrored(true);
    onError?.(event);
  };

  const responsive = getResponsiveSrcSet(src);
  const warmClass = warm ? 'img-warm' : '';
  const lqipClass = `img-lqip ${loaded ? 'is-loaded loaded' : 'is-loading'}`;
  const imgClassName = `${lqipClass} ${warmClass} ${className || ''}`.trim();

  const sharedProps = {
    ...props,
    // `alt` non sta qui: ogni tag immagine lo passa esplicito prima dello
    // spread, e averlo in entrambi i posti lo faceva riscrivere con lo stesso
    // valore. E' destrutturato dalle props a :71, quindi `...props` non lo porta.
    className: imgClassName,
    loading: priority ? ('eager' as const) : ('lazy' as const),
    decoding: 'async' as const,
    fetchPriority: priority ? ('high' as const) : ('auto' as const),
    referrerPolicy: 'no-referrer' as const,
    width,
    height,
    onLoad: handleLoad,
    onError: handleError,
    'data-loaded': loaded ? 'true' : 'false',
  };

  if (responsive) {
    const resolvedSizes = sizes || '(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw';

    if (responsive.avifSrcSet) {
      return (
        <picture>
          <source type="image/avif" srcSet={responsive.avifSrcSet} sizes={resolvedSizes} />
          <img
            alt={alt}
            src={responsive.defaultSrc}
            srcSet={responsive.srcSet}
            sizes={resolvedSizes}
            {...sharedProps}
          />
        </picture>
      );
    }

    return (
      <img
        alt={alt}
        src={responsive.defaultSrc}
        srcSet={responsive.srcSet}
        sizes={resolvedSizes}
        {...sharedProps}
      />
    );
  }

  const localMatch = /^\/(?:images\/[^?#]+)\.(png|jpe?g|webp)(\?[^#]*)?(#.*)?$/i.exec(src);
  if (localMatch) {
    const avifSrc = src.replace(/\.(png|jpe?g|webp)(?=$|[?#])/i, '.avif');
    const webpSrc = src.replace(/\.(png|jpe?g|webp)(?=$|[?#])/i, '.webp');
    const resolvedSizes = sizes || '(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw';
    const localSrcSet = (ext: 'avif' | 'webp') => {
      const variants =
        responsiveWidths?.map(
          (w) => `${src.replace(/\.(png|jpe?g|webp)(?=$|[?#])/i, `-${w}.${ext}`)} ${w}w`
        ) ?? [];
      // La sorgente base (già ottimizzata da optimize-images.mjs, nessun
      // suffisso) entra nel srcSet come variante più larga.
      if (baseWidth) {
        variants.push(`${src.replace(/\.(png|jpe?g|webp)(?=$|[?#])/i, `.${ext}`)} ${baseWidth}w`);
      }
      return variants.length > 0 ? variants.join(', ') : undefined;
    };
    const hasLocalVariants = Boolean(responsiveWidths || baseWidth);

    return (
      <picture>
        <source type="image/avif" srcSet={localSrcSet('avif') || avifSrc} sizes={resolvedSizes} />
        {!/\.webp(?:$|[?#])/i.test(src) && (
          <source type="image/webp" srcSet={localSrcSet('webp') || webpSrc} sizes={resolvedSizes} />
        )}
        <img
          alt={alt}
          src={src}
          srcSet={/\.webp(?:$|[?#])/i.test(src) ? localSrcSet('webp') : undefined}
          sizes={hasLocalVariants ? resolvedSizes : undefined}
          {...sharedProps}
        />
      </picture>
    );
  }

  return <img alt={alt} src={src} {...sharedProps} />;
}
